// 大会設定のデフォルト（KVが空のときのGETフォールバック＆管理画面の初期シード）
// teams/groups の値は public/data.js と一致させること（Task 3 で転記）。
export const DEFAULT_CONFIG = {
  version: 1,
  updatedAt: null,
  teams: [
    { code: 'MEX', ja: 'メキシコ',             flag: '🇲🇽', c: '#1E7C45' },
    { code: 'KOR', ja: '韓国',                 flag: '🇰🇷', c: '#C8334A' },
    { code: 'RSA', ja: '南アフリカ',           flag: '🇿🇦', c: '#007A4D' },
    { code: 'CZE', ja: 'チェコ',               flag: '🇨🇿', c: '#2C5BB5' },
    { code: 'CAN', ja: 'カナダ',               flag: '🇨🇦', c: '#D9322E' },
    { code: 'SUI', ja: 'スイス',               flag: '🇨🇭', c: '#D62B30' },
    { code: 'QAT', ja: 'カタール',             flag: '🇶🇦', c: '#8A1538' },
    { code: 'BIH', ja: 'ボスニア・ヘルツェゴビナ', flag: '🇧🇦', c: '#2E4A9E' },
    { code: 'BRA', ja: 'ブラジル',             flag: '🇧🇷', c: '#FBE14B' },
    { code: 'MAR', ja: 'モロッコ',             flag: '🇲🇦', c: '#16704A' },
    { code: 'SCO', ja: 'スコットランド',       flag: '🏴\u{E0067}\u{E0062}\u{E0073}\u{E0063}\u{E0074}\u{E007F}', c: '#2A5BA8' },
    { code: 'HAI', ja: 'ハイチ',               flag: '🇭🇹', c: '#1E50E6' },
    { code: 'USA', ja: 'アメリカ',             flag: '🇺🇸', c: '#3B4C99' },
    { code: 'AUS', ja: 'オーストラリア',       flag: '🇦🇺', c: '#E0A100' },
    { code: 'PAR', ja: 'パラグアイ',           flag: '🇵🇾', c: '#C8334A' },
    { code: 'TUR', ja: 'トルコ',               flag: '🇹🇷', c: '#E03A3A' },
    { code: 'GER', ja: 'ドイツ',               flag: '🇩🇪', c: '#3A3A3A' },
    { code: 'ECU', ja: 'エクアドル',           flag: '🇪🇨', c: '#F4C430' },
    { code: 'CIV', ja: 'コートジボワール',     flag: '🇨🇮', c: '#F5821F' },
    { code: 'CUW', ja: 'キュラソー',           flag: '🇨🇼', c: '#1B2A6B' },
    { code: 'NED', ja: 'オランダ',             flag: '🇳🇱', c: '#F5821F' },
    { code: 'JPN', ja: '日本',                 flag: '🇯🇵', c: '#1B2A6B' },
    { code: 'TUN', ja: 'チュニジア',           flag: '🇹🇳', c: '#C8334A' },
    { code: 'SWE', ja: 'スウェーデン',         flag: '🇸🇪', c: '#2C7DB5' },
    { code: 'BEL', ja: 'ベルギー',             flag: '🇧🇪', c: '#D62B30' },
    { code: 'IRN', ja: 'イラン',               flag: '🇮🇷', c: '#1E8A4C' },
    { code: 'EGY', ja: 'エジプト',             flag: '🇪🇬', c: '#C8334A' },
    { code: 'NZL', ja: 'ニュージーランド',     flag: '🇳🇿', c: '#1B2A6B' },
    { code: 'ESP', ja: 'スペイン',             flag: '🇪🇸', c: '#E03A3A' },
    { code: 'URU', ja: 'ウルグアイ',           flag: '🇺🇾', c: '#4FA0DA' },
    { code: 'KSA', ja: 'サウジアラビア',       flag: '🇸🇦', c: '#127A4A' },
    { code: 'CPV', ja: 'カーボベルデ',         flag: '🇨🇻', c: '#2D5BC4' },
    { code: 'FRA', ja: 'フランス',             flag: '🇫🇷', c: '#2D5BC4' },
    { code: 'SEN', ja: 'セネガル',             flag: '🇸🇳', c: '#1E8A4C' },
    { code: 'NOR', ja: 'ノルウェー',           flag: '🇳🇴', c: '#C63A4A' },
    { code: 'IRQ', ja: 'イラク',               flag: '🇮🇶', c: '#C8334A' },
    { code: 'ARG', ja: 'アルゼンチン',         flag: '🇦🇷', c: '#75AADB' },
    { code: 'AUT', ja: 'オーストリア',         flag: '🇦🇹', c: '#E64A4A' },
    { code: 'ALG', ja: 'アルジェリア',         flag: '🇩🇿', c: '#16704A' },
    { code: 'JOR', ja: 'ヨルダン',             flag: '🇯🇴', c: '#C8334A' },
    { code: 'POR', ja: 'ポルトガル',           flag: '🇵🇹', c: '#1E8A4C' },
    { code: 'COL', ja: 'コロンビア',           flag: '🇨🇴', c: '#F4C430' },
    { code: 'UZB', ja: 'ウズベキスタン',       flag: '🇺🇿', c: '#2C7DB5' },
    { code: 'COD', ja: 'DRコンゴ',             flag: '🇨🇩', c: '#2C9A4A' },
    { code: 'ENG', ja: 'イングランド',         flag: '🏴\u{E0067}\u{E0062}\u{E0065}\u{E006E}\u{E0067}\u{E007F}', c: '#E64A4A' },
    { code: 'CRO', ja: 'クロアチア',           flag: '🇭🇷', c: '#D1334A' },
    { code: 'PAN', ja: 'パナマ',               flag: '🇵🇦', c: '#C8334A' },
    { code: 'GHA', ja: 'ガーナ',               flag: '🇬🇭', c: '#D6334C' },
  ],
  groups: {
    A: ['MEX', 'KOR', 'RSA', 'CZE'],
    B: ['CAN', 'SUI', 'QAT', 'BIH'],
    C: ['BRA', 'MAR', 'SCO', 'HAI'],
    D: ['USA', 'AUS', 'PAR', 'TUR'],
    E: ['GER', 'ECU', 'CIV', 'CUW'],
    F: ['NED', 'JPN', 'TUN', 'SWE'],
    G: ['BEL', 'IRN', 'EGY', 'NZL'],
    H: ['ESP', 'URU', 'KSA', 'CPV'],
    I: ['FRA', 'SEN', 'NOR', 'IRQ'],
    J: ['ARG', 'AUT', 'ALG', 'JOR'],
    K: ['POR', 'COL', 'UZB', 'COD'],
    L: ['ENG', 'CRO', 'PAN', 'GHA'],
  },
  groupResult: { A: [], B: [], C: [], D: [], E: [], F: [], G: [], H: [], I: [], J: [], K: [], L: [] },
  scorerSuggest: [
    'ムバッペ', 'ハーランド', 'メッシ', 'ヴィニシウス', 'ヤマル',
    'ベリンガム', 'ケイン', 'グリーズマン', 'ラウタロ', '三笘',
  ],
  result: {
    champion: 'ARG',
    runnerUp: 'FRA',
    topScorer: 'ムバッペ',
    bracket: {
      r16:   ['BRA', 'POR', 'ARG', 'NED', 'FRA', 'ESP', 'ENG', 'GER'],
      qf:    ['BRA', 'ARG', 'FRA', 'ENG'],
      sf:    ['ARG', 'FRA'],
      final: ['ARG'],
    },
  },
  schedule: [],
  r16Teams: [],
};
