// 大会設定のデフォルト（KVが空のときのGETフォールバック＆管理画面の初期シード）
// teams/groups の値は public/data.js と一致させること（Task 3 で転記）。
export const DEFAULT_CONFIG = {
	version: 1,
	updatedAt: null,
	teams: [
		{ code: "MEX", ja: "メキシコ", flag: "🇲🇽", c: "#1E7C45" },
		{ code: "KOR", ja: "韓国", flag: "🇰🇷", c: "#C8334A" },
		{ code: "RSA", ja: "南アフリカ", flag: "🇿🇦", c: "#007A4D" },
		{ code: "CZE", ja: "チェコ", flag: "🇨🇿", c: "#2C5BB5" },
		{ code: "CAN", ja: "カナダ", flag: "🇨🇦", c: "#D9322E" },
		{ code: "SUI", ja: "スイス", flag: "🇨🇭", c: "#D62B30" },
		{ code: "QAT", ja: "カタール", flag: "🇶🇦", c: "#8A1538" },
		{ code: "BIH", ja: "ボスニア・ヘルツェゴビナ", flag: "🇧🇦", c: "#2E4A9E" },
		{ code: "BRA", ja: "ブラジル", flag: "🇧🇷", c: "#FBE14B" },
		{ code: "MAR", ja: "モロッコ", flag: "🇲🇦", c: "#16704A" },
		{
			code: "SCO",
			ja: "スコットランド",
			flag: "🏴\u{E0067}\u{E0062}\u{E0073}\u{E0063}\u{E0074}\u{E007F}",
			c: "#2A5BA8",
		},
		{ code: "HAI", ja: "ハイチ", flag: "🇭🇹", c: "#1E50E6" },
		{ code: "USA", ja: "アメリカ", flag: "🇺🇸", c: "#3B4C99" },
		{ code: "AUS", ja: "オーストラリア", flag: "🇦🇺", c: "#E0A100" },
		{ code: "PAR", ja: "パラグアイ", flag: "🇵🇾", c: "#C8334A" },
		{ code: "TUR", ja: "トルコ", flag: "🇹🇷", c: "#E03A3A" },
		{ code: "GER", ja: "ドイツ", flag: "🇩🇪", c: "#3A3A3A" },
		{ code: "ECU", ja: "エクアドル", flag: "🇪🇨", c: "#F4C430" },
		{ code: "CIV", ja: "コートジボワール", flag: "🇨🇮", c: "#F5821F" },
		{ code: "CUW", ja: "キュラソー", flag: "🇨🇼", c: "#1B2A6B" },
		{ code: "NED", ja: "オランダ", flag: "🇳🇱", c: "#F5821F" },
		{ code: "JPN", ja: "日本", flag: "🇯🇵", c: "#1B2A6B" },
		{ code: "TUN", ja: "チュニジア", flag: "🇹🇳", c: "#C8334A" },
		{ code: "SWE", ja: "スウェーデン", flag: "🇸🇪", c: "#2C7DB5" },
		{ code: "BEL", ja: "ベルギー", flag: "🇧🇪", c: "#D62B30" },
		{ code: "IRN", ja: "イラン", flag: "🇮🇷", c: "#1E8A4C" },
		{ code: "EGY", ja: "エジプト", flag: "🇪🇬", c: "#C8334A" },
		{ code: "NZL", ja: "ニュージーランド", flag: "🇳🇿", c: "#1B2A6B" },
		{ code: "ESP", ja: "スペイン", flag: "🇪🇸", c: "#E03A3A" },
		{ code: "URU", ja: "ウルグアイ", flag: "🇺🇾", c: "#4FA0DA" },
		{ code: "KSA", ja: "サウジアラビア", flag: "🇸🇦", c: "#127A4A" },
		{ code: "CPV", ja: "カーボベルデ", flag: "🇨🇻", c: "#2D5BC4" },
		{ code: "FRA", ja: "フランス", flag: "🇫🇷", c: "#2D5BC4" },
		{ code: "SEN", ja: "セネガル", flag: "🇸🇳", c: "#1E8A4C" },
		{ code: "NOR", ja: "ノルウェー", flag: "🇳🇴", c: "#C63A4A" },
		{ code: "IRQ", ja: "イラク", flag: "🇮🇶", c: "#C8334A" },
		{ code: "ARG", ja: "アルゼンチン", flag: "🇦🇷", c: "#75AADB" },
		{ code: "AUT", ja: "オーストリア", flag: "🇦🇹", c: "#E64A4A" },
		{ code: "ALG", ja: "アルジェリア", flag: "🇩🇿", c: "#16704A" },
		{ code: "JOR", ja: "ヨルダン", flag: "🇯🇴", c: "#C8334A" },
		{ code: "POR", ja: "ポルトガル", flag: "🇵🇹", c: "#1E8A4C" },
		{ code: "COL", ja: "コロンビア", flag: "🇨🇴", c: "#F4C430" },
		{ code: "UZB", ja: "ウズベキスタン", flag: "🇺🇿", c: "#2C7DB5" },
		{ code: "COD", ja: "DRコンゴ", flag: "🇨🇩", c: "#2C9A4A" },
		{
			code: "ENG",
			ja: "イングランド",
			flag: "🏴\u{E0067}\u{E0062}\u{E0065}\u{E006E}\u{E0067}\u{E007F}",
			c: "#E64A4A",
		},
		{ code: "CRO", ja: "クロアチア", flag: "🇭🇷", c: "#D1334A" },
		{ code: "PAN", ja: "パナマ", flag: "🇵🇦", c: "#C8334A" },
		{ code: "GHA", ja: "ガーナ", flag: "🇬🇭", c: "#D6334C" },
	],
	groups: {
		A: ["MEX", "KOR", "RSA", "CZE"],
		B: ["CAN", "SUI", "QAT", "BIH"],
		C: ["BRA", "MAR", "SCO", "HAI"],
		D: ["USA", "AUS", "PAR", "TUR"],
		E: ["GER", "ECU", "CIV", "CUW"],
		F: ["NED", "JPN", "TUN", "SWE"],
		G: ["BEL", "IRN", "EGY", "NZL"],
		H: ["ESP", "URU", "KSA", "CPV"],
		I: ["FRA", "SEN", "NOR", "IRQ"],
		J: ["ARG", "AUT", "ALG", "JOR"],
		K: ["POR", "COL", "UZB", "COD"],
		L: ["ENG", "CRO", "PAN", "GHA"],
	},
	groupResult: {
		A: [],
		B: [],
		C: [],
		D: [],
		E: [],
		F: [],
		G: [],
		H: [],
		I: [],
		J: [],
		K: [],
		L: [],
	},
	// 大会の確定結果。空＝未確定（採点は実際に入力された結果のみで行われる）。
	// 管理画面で試合スコア／到達チーム／優勝などを入力すると埋まり、ランキングへ反映される。
	result: {
		champion: null,
		runnerUp: null,
		topScorer: "",
		bracket: { r16: [], qf: [], sf: [], final: [] },
		knockout: { r32: [], r16: [], qf: [], sf: [] },
		thirdAssign: {},
		thirdGroups: [],
	},
	groupMatches: {},
	scorers: [],
	aliases: [],
	// FIFA 2026 W杯 公式試合日程（全104試合）。日付(date)・時刻(time)はすべて日本時間(JST, UTC+9)。
	//   現地時刻＋UTCオフセットを JST へ変換済み（UTC−4→+13h, −5→+14h, −6→+15h, −7→+16h）。
	//   米国の夜開催が大半のため、JSTでは大半が「現地翌日の早朝〜昼」になる。
	// グループステージ(72)は最終ドロー確定の対戦カード（a/b は teams の3文字コード、round はグループ記号）。
	// ノックアウト(73-104)はチーム未確定のため a/b に確定済みスロット表記を入れる:
	//   1X=グループX 1位 / 2X=グループX 2位 / 3(...)=該当グループ群の3位 / W##=第##試合の勝者 / L##=敗者。
	// note は「#試合番号 開催地」。出典: Wikipedia 2026 FIFA World Cup 各グループ/ノックアウト公式マッチ表。
	schedule: [
		// ── グループステージ Matchday 1 ──
		{
			date: "2026-06-12",
			time: "04:00",
			round: "A",
			a: "MEX",
			b: "RSA",
			note: "Mexico City",
		},
		{
			date: "2026-06-12",
			time: "11:00",
			round: "A",
			a: "KOR",
			b: "CZE",
			note: "Zapopan",
		},
		{
			date: "2026-06-13",
			time: "04:00",
			round: "B",
			a: "CAN",
			b: "BIH",
			note: "Toronto",
		},
		{
			date: "2026-06-13",
			time: "10:00",
			round: "D",
			a: "USA",
			b: "PAR",
			note: "Inglewood",
		},
		{
			date: "2026-06-14",
			time: "04:00",
			round: "B",
			a: "QAT",
			b: "SUI",
			note: "Santa Clara",
		},
		{
			date: "2026-06-14",
			time: "07:00",
			round: "C",
			a: "BRA",
			b: "MAR",
			note: "East Rutherford",
		},
		{
			date: "2026-06-14",
			time: "10:00",
			round: "C",
			a: "HAI",
			b: "SCO",
			note: "Foxborough",
		},
		{
			date: "2026-06-14",
			time: "13:00",
			round: "D",
			a: "AUS",
			b: "TUR",
			note: "Vancouver",
		},
		{
			date: "2026-06-15",
			time: "02:00",
			round: "E",
			a: "GER",
			b: "CUW",
			note: "Houston",
		},
		{
			date: "2026-06-15",
			time: "05:00",
			round: "F",
			a: "NED",
			b: "JPN",
			note: "Arlington",
		},
		{
			date: "2026-06-15",
			time: "08:00",
			round: "E",
			a: "CIV",
			b: "ECU",
			note: "Philadelphia",
		},
		{
			date: "2026-06-15",
			time: "11:00",
			round: "F",
			a: "SWE",
			b: "TUN",
			note: "Guadalupe",
		},
		{
			date: "2026-06-16",
			time: "01:00",
			round: "H",
			a: "ESP",
			b: "CPV",
			note: "Atlanta",
		},
		{
			date: "2026-06-16",
			time: "04:00",
			round: "G",
			a: "BEL",
			b: "EGY",
			note: "Seattle",
		},
		{
			date: "2026-06-16",
			time: "07:00",
			round: "H",
			a: "KSA",
			b: "URU",
			note: "Miami Gardens",
		},
		{
			date: "2026-06-16",
			time: "10:00",
			round: "G",
			a: "IRN",
			b: "NZL",
			note: "Inglewood",
		},
		{
			date: "2026-06-17",
			time: "04:00",
			round: "I",
			a: "FRA",
			b: "SEN",
			note: "East Rutherford",
		},
		{
			date: "2026-06-17",
			time: "07:00",
			round: "I",
			a: "IRQ",
			b: "NOR",
			note: "Foxborough",
		},
		{
			date: "2026-06-17",
			time: "10:00",
			round: "J",
			a: "ARG",
			b: "ALG",
			note: "Kansas City",
		},
		{
			date: "2026-06-17",
			time: "13:00",
			round: "J",
			a: "AUT",
			b: "JOR",
			note: "Santa Clara",
		},
		{
			date: "2026-06-18",
			time: "02:00",
			round: "K",
			a: "POR",
			b: "COD",
			note: "Houston",
		},
		{
			date: "2026-06-18",
			time: "05:00",
			round: "L",
			a: "ENG",
			b: "CRO",
			note: "Arlington",
		},
		{
			date: "2026-06-18",
			time: "08:00",
			round: "L",
			a: "GHA",
			b: "PAN",
			note: "Toronto",
		},
		{
			date: "2026-06-18",
			time: "11:00",
			round: "K",
			a: "UZB",
			b: "COL",
			note: "Mexico City",
		},
		// ── グループステージ Matchday 2 ──
		{
			date: "2026-06-19",
			time: "01:00",
			round: "A",
			a: "CZE",
			b: "RSA",
			note: "Atlanta",
		},
		{
			date: "2026-06-19",
			time: "04:00",
			round: "B",
			a: "SUI",
			b: "BIH",
			note: "Inglewood",
		},
		{
			date: "2026-06-19",
			time: "07:00",
			round: "B",
			a: "CAN",
			b: "QAT",
			note: "Vancouver",
		},
		{
			date: "2026-06-19",
			time: "10:00",
			round: "A",
			a: "MEX",
			b: "KOR",
			note: "Zapopan",
		},
		{
			date: "2026-06-20",
			time: "04:00",
			round: "D",
			a: "USA",
			b: "AUS",
			note: "Seattle",
		},
		{
			date: "2026-06-20",
			time: "07:00",
			round: "C",
			a: "SCO",
			b: "MAR",
			note: "Foxborough",
		},
		{
			date: "2026-06-20",
			time: "09:30",
			round: "C",
			a: "BRA",
			b: "HAI",
			note: "Philadelphia",
		},
		{
			date: "2026-06-20",
			time: "12:00",
			round: "D",
			a: "TUR",
			b: "PAR",
			note: "Santa Clara",
		},
		{
			date: "2026-06-21",
			time: "02:00",
			round: "F",
			a: "NED",
			b: "SWE",
			note: "Houston",
		},
		{
			date: "2026-06-21",
			time: "05:00",
			round: "E",
			a: "GER",
			b: "CIV",
			note: "Toronto",
		},
		{
			date: "2026-06-21",
			time: "09:00",
			round: "E",
			a: "ECU",
			b: "CUW",
			note: "Kansas City",
		},
		{
			date: "2026-06-21",
			time: "13:00",
			round: "F",
			a: "TUN",
			b: "JPN",
			note: "Guadalupe",
		},
		{
			date: "2026-06-22",
			time: "01:00",
			round: "H",
			a: "ESP",
			b: "KSA",
			note: "Atlanta",
		},
		{
			date: "2026-06-22",
			time: "04:00",
			round: "G",
			a: "BEL",
			b: "IRN",
			note: "Inglewood",
		},
		{
			date: "2026-06-22",
			time: "07:00",
			round: "H",
			a: "URU",
			b: "CPV",
			note: "Miami Gardens",
		},
		{
			date: "2026-06-22",
			time: "10:00",
			round: "G",
			a: "NZL",
			b: "EGY",
			note: "Vancouver",
		},
		{
			date: "2026-06-23",
			time: "02:00",
			round: "J",
			a: "ARG",
			b: "AUT",
			note: "Arlington",
		},
		{
			date: "2026-06-23",
			time: "06:00",
			round: "I",
			a: "FRA",
			b: "IRQ",
			note: "Philadelphia",
		},
		{
			date: "2026-06-23",
			time: "09:00",
			round: "I",
			a: "NOR",
			b: "SEN",
			note: "East Rutherford",
		},
		{
			date: "2026-06-23",
			time: "12:00",
			round: "J",
			a: "JOR",
			b: "ALG",
			note: "Santa Clara",
		},
		{
			date: "2026-06-24",
			time: "02:00",
			round: "K",
			a: "POR",
			b: "UZB",
			note: "Houston",
		},
		{
			date: "2026-06-24",
			time: "05:00",
			round: "L",
			a: "ENG",
			b: "GHA",
			note: "Foxborough",
		},
		{
			date: "2026-06-24",
			time: "08:00",
			round: "L",
			a: "PAN",
			b: "CRO",
			note: "Toronto",
		},
		{
			date: "2026-06-24",
			time: "11:00",
			round: "K",
			a: "COL",
			b: "COD",
			note: "Zapopan",
		},
		// ── グループステージ Matchday 3（同組2試合は同時刻キックオフ）──
		{
			date: "2026-06-25",
			time: "04:00",
			round: "B",
			a: "SUI",
			b: "CAN",
			note: "Vancouver",
		},
		{
			date: "2026-06-25",
			time: "04:00",
			round: "B",
			a: "BIH",
			b: "QAT",
			note: "Seattle",
		},
		{
			date: "2026-06-25",
			time: "07:00",
			round: "C",
			a: "SCO",
			b: "BRA",
			note: "Miami Gardens",
		},
		{
			date: "2026-06-25",
			time: "07:00",
			round: "C",
			a: "MAR",
			b: "HAI",
			note: "Atlanta",
		},
		{
			date: "2026-06-25",
			time: "10:00",
			round: "A",
			a: "CZE",
			b: "MEX",
			note: "Mexico City",
		},
		{
			date: "2026-06-25",
			time: "10:00",
			round: "A",
			a: "RSA",
			b: "KOR",
			note: "Guadalupe",
		},
		{
			date: "2026-06-26",
			time: "05:00",
			round: "E",
			a: "ECU",
			b: "GER",
			note: "East Rutherford",
		},
		{
			date: "2026-06-26",
			time: "05:00",
			round: "E",
			a: "CUW",
			b: "CIV",
			note: "Philadelphia",
		},
		{
			date: "2026-06-26",
			time: "08:00",
			round: "F",
			a: "JPN",
			b: "SWE",
			note: "Arlington",
		},
		{
			date: "2026-06-26",
			time: "08:00",
			round: "F",
			a: "TUN",
			b: "NED",
			note: "Kansas City",
		},
		{
			date: "2026-06-26",
			time: "11:00",
			round: "D",
			a: "TUR",
			b: "USA",
			note: "Inglewood",
		},
		{
			date: "2026-06-26",
			time: "11:00",
			round: "D",
			a: "PAR",
			b: "AUS",
			note: "Santa Clara",
		},
		{
			date: "2026-06-27",
			time: "04:00",
			round: "I",
			a: "NOR",
			b: "FRA",
			note: "Foxborough",
		},
		{
			date: "2026-06-27",
			time: "04:00",
			round: "I",
			a: "SEN",
			b: "IRQ",
			note: "Toronto",
		},
		{
			date: "2026-06-27",
			time: "09:00",
			round: "H",
			a: "CPV",
			b: "KSA",
			note: "Houston",
		},
		{
			date: "2026-06-27",
			time: "09:00",
			round: "H",
			a: "URU",
			b: "ESP",
			note: "Zapopan",
		},
		{
			date: "2026-06-27",
			time: "12:00",
			round: "G",
			a: "EGY",
			b: "IRN",
			note: "Seattle",
		},
		{
			date: "2026-06-27",
			time: "12:00",
			round: "G",
			a: "NZL",
			b: "BEL",
			note: "Vancouver",
		},
		{
			date: "2026-06-28",
			time: "06:00",
			round: "L",
			a: "PAN",
			b: "ENG",
			note: "East Rutherford",
		},
		{
			date: "2026-06-28",
			time: "06:00",
			round: "L",
			a: "CRO",
			b: "GHA",
			note: "Philadelphia",
		},
		{
			date: "2026-06-28",
			time: "08:30",
			round: "K",
			a: "COL",
			b: "POR",
			note: "Miami Gardens",
		},
		{
			date: "2026-06-28",
			time: "08:30",
			round: "K",
			a: "COD",
			b: "UZB",
			note: "Atlanta",
		},
		{
			date: "2026-06-28",
			time: "11:00",
			round: "J",
			a: "ALG",
			b: "AUT",
			note: "Kansas City",
		},
		{
			date: "2026-06-28",
			time: "11:00",
			round: "J",
			a: "JOR",
			b: "ARG",
			note: "Arlington",
		},
		// ── ベスト32（Round of 32）──
		{
			date: "2026-06-29",
			time: "04:00",
			round: "R32",
			a: "2A",
			b: "2B",
			note: "#73 Inglewood",
		},
		{
			date: "2026-06-30",
			time: "05:30",
			round: "R32",
			a: "1E",
			b: "3(A/B/C/D/F)",
			note: "#74 Foxborough",
		},
		{
			date: "2026-06-30",
			time: "10:00",
			round: "R32",
			a: "1F",
			b: "2C",
			note: "#75 Guadalupe",
		},
		{
			date: "2026-06-30",
			time: "02:00",
			round: "R32",
			a: "1C",
			b: "2F",
			note: "#76 Houston",
		},
		{
			date: "2026-07-01",
			time: "06:00",
			round: "R32",
			a: "1I",
			b: "3(C/D/F/G/H)",
			note: "#77 East Rutherford",
		},
		{
			date: "2026-07-01",
			time: "02:00",
			round: "R32",
			a: "2E",
			b: "2I",
			note: "#78 Arlington",
		},
		{
			date: "2026-07-01",
			time: "10:00",
			round: "R32",
			a: "1A",
			b: "3(C/E/F/H/I)",
			note: "#79 Mexico City",
		},
		{
			date: "2026-07-02",
			time: "01:00",
			round: "R32",
			a: "1L",
			b: "3(E/H/I/J/K)",
			note: "#80 Atlanta",
		},
		{
			date: "2026-07-02",
			time: "09:00",
			round: "R32",
			a: "1D",
			b: "3(B/E/F/I/J)",
			note: "#81 Santa Clara",
		},
		{
			date: "2026-07-02",
			time: "05:00",
			round: "R32",
			a: "1G",
			b: "3(A/E/H/I/J)",
			note: "#82 Seattle",
		},
		{
			date: "2026-07-03",
			time: "08:00",
			round: "R32",
			a: "2K",
			b: "2L",
			note: "#83 Toronto",
		},
		{
			date: "2026-07-03",
			time: "04:00",
			round: "R32",
			a: "1H",
			b: "2J",
			note: "#84 Inglewood",
		},
		{
			date: "2026-07-03",
			time: "12:00",
			round: "R32",
			a: "1B",
			b: "3(E/F/G/I/J)",
			note: "#85 Vancouver",
		},
		{
			date: "2026-07-04",
			time: "07:00",
			round: "R32",
			a: "1J",
			b: "2H",
			note: "#86 Miami Gardens",
		},
		{
			date: "2026-07-04",
			time: "10:30",
			round: "R32",
			a: "1K",
			b: "3(D/E/I/J/L)",
			note: "#87 Kansas City",
		},
		{
			date: "2026-07-04",
			time: "03:00",
			round: "R32",
			a: "2D",
			b: "2G",
			note: "#88 Arlington",
		},
		// ── ベスト16（Round of 16）──
		{
			date: "2026-07-05",
			time: "06:00",
			round: "R16",
			a: "W74",
			b: "W77",
			note: "#89 Philadelphia",
		},
		{
			date: "2026-07-05",
			time: "02:00",
			round: "R16",
			a: "W73",
			b: "W75",
			note: "#90 Houston",
		},
		{
			date: "2026-07-06",
			time: "05:00",
			round: "R16",
			a: "W76",
			b: "W78",
			note: "#91 East Rutherford",
		},
		{
			date: "2026-07-06",
			time: "09:00",
			round: "R16",
			a: "W79",
			b: "W80",
			note: "#92 Mexico City",
		},
		{
			date: "2026-07-07",
			time: "04:00",
			round: "R16",
			a: "W83",
			b: "W84",
			note: "#93 Arlington",
		},
		{
			date: "2026-07-07",
			time: "09:00",
			round: "R16",
			a: "W81",
			b: "W82",
			note: "#94 Seattle",
		},
		{
			date: "2026-07-08",
			time: "01:00",
			round: "R16",
			a: "W86",
			b: "W88",
			note: "#95 Atlanta",
		},
		{
			date: "2026-07-08",
			time: "05:00",
			round: "R16",
			a: "W85",
			b: "W87",
			note: "#96 Vancouver",
		},
		// ── 準々決勝（Quarter-finals）──
		{
			date: "2026-07-10",
			time: "05:00",
			round: "QF",
			a: "W89",
			b: "W90",
			note: "#97 Foxborough",
		},
		{
			date: "2026-07-11",
			time: "04:00",
			round: "QF",
			a: "W93",
			b: "W94",
			note: "#98 Inglewood",
		},
		{
			date: "2026-07-12",
			time: "06:00",
			round: "QF",
			a: "W91",
			b: "W92",
			note: "#99 Miami Gardens",
		},
		{
			date: "2026-07-12",
			time: "10:00",
			round: "QF",
			a: "W95",
			b: "W96",
			note: "#100 Kansas City",
		},
		// ── 準決勝（Semi-finals）──
		{
			date: "2026-07-15",
			time: "04:00",
			round: "SF",
			a: "W97",
			b: "W98",
			note: "#101 Arlington",
		},
		{
			date: "2026-07-16",
			time: "04:00",
			round: "SF",
			a: "W99",
			b: "W100",
			note: "#102 Atlanta",
		},
		// ── 3位決定戦・決勝 ──
		{
			date: "2026-07-19",
			time: "06:00",
			round: "3位",
			a: "L101",
			b: "L102",
			note: "#103 Miami Gardens",
		},
		{
			date: "2026-07-20",
			time: "04:00",
			round: "決勝",
			a: "W101",
			b: "W102",
			note: "#104 East Rutherford",
		},
	],
	// 国別選手名簿（code -> [{ name, pos }]）。pos は GK/DF/MF/FW。
	// FIFA 公式 SquadLists を Phase C で転記。
	squads: {
		MEX: [
			{ pos: "GK", name: "R. RANGEL", club: "CD Guadalajara (MEX)" },
			{ pos: "DF", name: "J. SÁNCHEZ", club: "PAOK Saloniki (GRE)" },
			{ pos: "DF", name: "C. MONTES", club: "FC Lokomotiv Moscow (RUS)" },
			{ pos: "DF", name: "E. ÁLVAREZ", club: "Fenerbahçe SK (TUR)" },
			{ pos: "DF", name: "J. VÁSQUEZ", club: "Genoa CFC (ITA)" },
			{ pos: "MF", name: "E. LIRA", club: "CF Cruz Azul (MEX)" },
			{ pos: "MF", name: "L. ROMO", club: "CD Guadalajara (MEX)" },
			{ pos: "MF", name: "FIDALGO", club: "Real Betis (ESP)" },
			{ pos: "FW", name: "RAÚL", club: "Fulham FC (ENG)" },
			{ pos: "FW", name: "A. VEGA", club: "Deportivo Toluca FC (MEX)" },
			{ pos: "FW", name: "S. GIMENEZ", club: "AC Milan (ITA)" },
			{ pos: "GK", name: "C. ACEVEDO", club: "Club Santos Laguna (MEX)" },
			{ pos: "GK", name: "G. OCHOA", club: "AEL Limassol (CYP)" },
			{ pos: "FW", name: "A. GONZÁLEZ", club: "CD Guadalajara (MEX)" },
			{ pos: "DF", name: "I. REYES", club: "Club América (MEX)" },
			{ pos: "FW", name: "J. QUIÑONES", club: "Al Qadsiah FC (KSA)" },
			{ pos: "MF", name: "ORBELÍN", club: "AEK Athens (GRE)" },
			{ pos: "MF", name: "O. VARGAS", club: "Atlético De Madrid (ESP)" },
			{ pos: "MF", name: "G. MORA", club: "Club Tijuana (MEX)" },
			{ pos: "DF", name: "M. CHÁVEZ", club: "AZ Alkmaar (NED)" },
			{ pos: "FW", name: "C. HUERTA", club: "RSC Anderlecht (BEL)" },
			{ pos: "FW", name: "G. MARTÍNEZ", club: "Pumas UNAM (MEX)" },
			{ pos: "DF", name: "J. GALLARDO", club: "Deportivo Toluca FC (MEX)" },
			{ pos: "MF", name: "L. CHÁVEZ", club: "FC Dynamo Moscow (RUS)" },
			{ pos: "FW", name: "R. ALVARADO", club: "CD Guadalajara (MEX)" },
			{ pos: "MF", name: "B. GUTIÉRREZ", club: "CD Guadalajara (MEX)" },
		],
		KOR: [
			{ pos: "GK", name: "SEUNGGYU", club: "FC Tokyo (JPN)" },
			{ pos: "DF", name: "HANBEOM", club: "FC Midtjylland (DEN)" },
			{ pos: "MF", name: "GIHYUK", club: "Gangwon FC (KOR)" },
			{ pos: "DF", name: "MINJAE", club: "FC Bayern München (GER)" },
			{ pos: "DF", name: "TAEHYEON", club: "Kashima Antlers (JPN)" },
			{ pos: "MF", name: "INBEOM", club: "Feyenoord Rotterdam (NED)" },
			{ pos: "FW", name: "HEUNGMIN", club: "LAFC (USA)" },
			{ pos: "MF", name: "SEUNGHO", club: "Birmingham City FC (ENG)" },
			{ pos: "FW", name: "GUESUNG", club: "FC Midtjylland (DEN)" },
			{ pos: "MF", name: "JAESUNG", club: "1. FSV Mainz 05 (GER)" },
			{ pos: "MF", name: "HEECHAN", club: "Wolverhampton Wanderers FC (ENG)" },
			{ pos: "GK", name: "BUMKEUN", club: "Jeonbuk Hyundai Motors FC (KOR)" },
			{ pos: "DF", name: "TAESEOK", club: "FK Austria Wien (AUT)" },
			{ pos: "DF", name: "WIJE", club: "Jeonbuk Hyundai Motors FC (KOR)" },
			{ pos: "DF", name: "MOONHWAN", club: "Daejeon Hana Citizen FC (KOR)" },
			{ pos: "DF", name: "JINSEOB", club: "Zhejiang FC (CHN)" },
			{ pos: "MF", name: "JUNHO", club: "Stoke City FC (ENG)" },
			{ pos: "FW", name: "HYEONGYU", club: "Beşiktaş JK (TUR)" },
			{ pos: "MF", name: "KANGIN", club: "Paris Saint-Germain (FRA)" },
			{ pos: "MF", name: "HYUNJUN", club: "Celtic FC (SCO)" },
			{ pos: "GK", name: "HYEONWOO", club: "Ulsan HD (KOR)" },
			{ pos: "DF", name: "YOUNGWOO", club: "FK Crvena Zvezda (SRB)" },
			{ pos: "DF", name: "JENS", club: "Borussia Mönchengladbach (GER)" },
			{ pos: "MF", name: "JINGYU", club: "Jeonbuk Hyundai Motors FC (KOR)" },
			{ pos: "MF", name: "JISUNG", club: "Swansea City AFC (WAL)" },
			{ pos: "MF", name: "DONGGYEONG", club: "Ulsan HD (KOR)" },
		],
		RSA: [
			{ pos: "GK", name: "WILLIAMS", club: "Mamelodi Sundowns FC (RSA)" },
			{ pos: "DF", name: "MATULUDI", club: "Polokwane City FC (RSA)" },
			{ pos: "DF", name: "NDAMANE", club: "Mamelodi Sundowns FC (RSA)" },
			{ pos: "MF", name: "MOKOENA", club: "Mamelodi Sundowns FC (RSA)" },
			{ pos: "MF", name: "MBATHA", club: "Orlando Pirates FC (RSA)" },
			{ pos: "DF", name: "MODIBA", club: "Mamelodi Sundowns FC (RSA)" },
			{ pos: "FW", name: "APPOLLIS", club: "Orlando Pirates FC (RSA)" },
			{ pos: "FW", name: "MOREMI", club: "Orlando Pirates FC (RSA)" },
			{ pos: "FW", name: "FOSTER", club: "Burnley FC (ENG)" },
			{ pos: "FW", name: "MOFOKENG", club: "Orlando Pirates FC (RSA)" },
			{ pos: "MF", name: "ZWANE", club: "Mamelodi Sundowns FC (RSA)" },
			{ pos: "FW", name: "MASEKO", club: "AEL Limassol (CYP)" },
			{ pos: "MF", name: "SITHOLE", club: "CD Tondela (POR)" },
			{ pos: "DF", name: "MBOKAZI", club: "Chicago Fire FC (USA)" },
			{ pos: "FW", name: "RAYNERS", club: "Mamelodi Sundowns FC (RSA)" },
			{ pos: "GK", name: "CHAINE", club: "Orlando Pirates FC (RSA)" },
			{ pos: "FW", name: "MAKGPA", club: "Orlando Pirates FC (RSA)" },
			{ pos: "DF", name: "KABINI", club: "Molde FK (NOR)" },
			{ pos: "DF", name: "SIBISI", club: "Orlando Pirates FC (RSA)" },
			{ pos: "DF", name: "MUDAU", club: "Mamelodi Sundowns FC (RSA)" },
			{ pos: "DF", name: "OKON", club: "Hannover 96 (GER)" },
			{ pos: "GK", name: "GOSS", club: "Siwelele FC (RSA)" },
			{ pos: "MF", name: "ADAMS", club: "Mamelodi Sundowns FC (RSA)" },
			{ pos: "DF", name: "MAKHANYA", club: "Philadelphia Union (USA)" },
			{ pos: "FW", name: "SEBELEBELE", club: "Orlando Pirates FC (RSA)" },
			{ pos: "DF", name: "CROSS", club: "Kaizer Chiefs FC (RSA)" },
		],
		CZE: [
			{ pos: "GK", name: "KOVÁŘ", club: "PSV Eindhoven (NED)" },
			{ pos: "DF", name: "ZIMA", club: "SK Slavia Praha (CZE)" },
			{ pos: "DF", name: "HOLEŠ", club: "SK Slavia Praha (CZE)" },
			{ pos: "DF", name: "HRANÁČ", club: "TSG Hoffenheim (GER)" },
			{ pos: "DF", name: "COUFAL", club: "TSG Hoffenheim (GER)" },
			{ pos: "DF", name: "CHALOUPEK", club: "SK Slavia Praha (CZE)" },
			{ pos: "DF", name: "KREJČÍ", club: "Wolverhampton Wanderers FC (ENG)" },
			{ pos: "MF", name: "DARIDA", club: "FC Hradec Králové (CZE)" },
			{ pos: "FW", name: "HLOŽEK", club: "TSG Hoffenheim (GER)" },
			{ pos: "FW", name: "SCHICK", club: "Bayer Leverkusen (GER)" },
			{ pos: "FW", name: "KUCHTA", club: "AC Sparta Praha (CZE)" },
			{ pos: "MF", name: "ČERV", club: "FC Viktoria Plzeň (CZE)" },
			{ pos: "FW", name: "CHYTIL", club: "SK Slavia Praha (CZE)" },
			{ pos: "DF", name: "JURÁSEK", club: "SK Slavia Praha (CZE)" },
			{ pos: "FW", name: "ŠULC", club: "Olympique Lyonnais (FRA)" },
			{ pos: "GK", name: "STANĚK", club: "SK Slavia Praha (CZE)" },
			{ pos: "MF", name: "PROVOD", club: "SK Slavia Praha (CZE)" },
			{ pos: "MF", name: "SADÍLEK", club: "SK Slavia Praha (CZE)" },
			{ pos: "FW", name: "CHORÝ", club: "SK Slavia Praha (CZE)" },
			{ pos: "DF", name: "ZELENÝ", club: "AC Sparta Praha (CZE)" },
			{ pos: "DF", name: "DOUDĚRA", club: "SK Slavia Praha (CZE)" },
			{ pos: "MF", name: "SOUČEK", club: "West Ham United FC (ENG)" },
			{ pos: "GK", name: "HORNÍČEK", club: "SC Braga (POR)" },
			{ pos: "MF", name: "SOJKA", club: "FC Viktoria Plzeň (CZE)" },
			{ pos: "MF", name: "SOCHŮREK", club: "AC Sparta Praha (CZE)" },
			{ pos: "FW", name: "VIŠINSKÝ", club: "FC Viktoria Plzeň (CZE)" },
		],
		CAN: [
			{ pos: "GK", name: "ST. CLAIR", club: "Inter Miami CF (USA)" },
			{ pos: "DF", name: "JOHNSTON", club: "Celtic FC (SCO)" },
			{ pos: "DF", name: "JONES", club: "Middlesbrough FC (ENG)" },
			{ pos: "DF", name: "DE FOUGEROLLES", club: "FCV Dender EH (BEL)" },
			{ pos: "DF", name: "WATERMAN", club: "Chicago Fire FC (USA)" },
			{ pos: "MF", name: "CHOINIÈRE", club: "LAFC (USA)" },
			{ pos: "MF", name: "EUSTÀQUIO", club: "LAFC (USA)" },
			{ pos: "MF", name: "KONÉ", club: "US Sassuolo (ITA)" },
			{ pos: "FW", name: "LARIN", club: "Southampton FC (ENG)" },
			{ pos: "FW", name: "J. DAVID", club: "Juventus FC (ITA)" },
			{ pos: "MF", name: "MILLAR", club: "Hull City FC (ENG)" },
			{ pos: "FW", name: "OLUWASEYI", club: "Villarreal CF (ESP)" },
			{ pos: "DF", name: "CORNELIUS", club: "Rangers FC (SCO)" },
			{ pos: "MF", name: "SHAFFELBURG", club: "LAFC (USA)" },
			{ pos: "DF", name: "BOMBITO", club: "OGC Nice (FRA)" },
			{ pos: "GK", name: "CRÉPEAU", club: "Orlando City SC (USA)" },
			{ pos: "FW", name: "BUCHANAN", club: "Villarreal CF (ESP)" },
			{ pos: "GK", name: "GOODMAN", club: "Barnsley (ENG)" },
			{ pos: "DF", name: "DAVIES", club: "FC Bayern München (GER)" },
			{ pos: "FW", name: "AHMED", club: "Norwich City FC (ENG)" },
			{ pos: "MF", name: "OSORIO", club: "Toronto FC (CAN)" },
			{ pos: "DF", name: "LARYEA", club: "Toronto FC (CAN)" },
			{ pos: "DF", name: "SIGUR", club: "HNK Hajduk Split (CRO)" },
			{ pos: "FW", name: "PROMISE", club: "Royale Union Saint-Gilloise (BEL)" },
			{ pos: "MF", name: "SALIBA", club: "RSC Anderlecht (BEL)" },
			{ pos: "MF", name: "MARCELO", club: "Tigres UANL (MEX)" },
		],
		SUI: [
			{ pos: "GK", name: "KOBEL", club: "Borussia Dortmund (GER)" },
			{ pos: "DF", name: "MUHEIM", club: "Hamburger SV (GER)" },
			{ pos: "DF", name: "WIDMER", club: "1. FSV Mainz 05 (GER)" },
			{ pos: "DF", name: "ELVEDI", club: "Borussia Mönchengladbach (GER)" },
			{ pos: "DF", name: "AKANJI", club: "FC Internazionale Milano (ITA)" },
			{ pos: "MF", name: "ZAKARIA", club: "AS Monaco (FRA)" },
			{ pos: "FW", name: "EMBOLO", club: "Stade Rennais FC (FRA)" },
			{ pos: "MF", name: "FREULER", club: "Bologna FC (ITA)" },
			{ pos: "MF", name: "MANZAMBI", club: "SC Freiburg (GER)" },
			{ pos: "MF", name: "XHAKA", club: "Sunderland AFC (ENG)" },
			{ pos: "FW", name: "NODYE", club: "Nottingham Forest FC (ENG)" },
			{ pos: "GK", name: "MV OGO", club: "FC Lorient (FRA)" },
			{ pos: "DF", name: "RODRIGUEZ", club: "Real Betis (ESP)" },
			{ pos: "MF", name: "JASHARI", club: "AC Milan (ITA)" },
			{ pos: "MF", name: "SOW", club: "Sevilla FC (ESP)" },
			{ pos: "FW", name: "FASSNACHT", club: "BSC Young Boys (SUI)" },
			{ pos: "FW", name: "VARGAS", club: "Sevilla FC (ESP)" },
			{ pos: "DF", name: "CÖMERT", club: "Valencia CF (ESP)" },
			{ pos: "FW", name: "OKAFOR", club: "Leeds United FC (ENG)" },
			{ pos: "MF", name: "AEBISCHER", club: "Pisa SC (ITA)" },
			{ pos: "GK", name: "KELLER", club: "BSC Young Boys (SUI)" },
			{ pos: "MF", name: "RIEDER", club: "FC Augsburg (GER)" },
			{ pos: "FW", name: "AMDOUNI", club: "Burnley FC (ENG)" },
			{ pos: "DF", name: "AMENDA", club: "Eintracht Frankfurt (GER)" },
			{ pos: "DF", name: "JAQUEZ", club: "VfB Stuttgart (GER)" },
			{ pos: "FW", name: "ITTEN", club: "Fortuna Düsseldorf (GER)" },
		],
		QAT: [
			{ pos: "GK", name: "ABUNADA", club: "Al Rayyan SC (QAT)" },
			{ pos: "DF", name: "PEDRO", club: "Al Sadd SC (QAT)" },
			{ pos: "DF", name: "L.MENDES", club: "Al Wakrah SC (QAT)" },
			{ pos: "DF", name: "GUEYE", club: "Al Arabi SC (QAT)" },
			{ pos: "DF", name: "JASSEM", club: "Al Rayyan SC (QAT)" },
			{ pos: "MF", name: "A. AZIZ", club: "Al Rayyan SC (QAT)" },
			{ pos: "FW", name: "ALAAELDIN", club: "Al Rayyan SC (QAT)" },
			{ pos: "FW", name: "EDMILSON JR.", club: "Al Duhail SC (QAT)" },
			{ pos: "FW", name: "MUNTARI", club: "Al Gharafa SC (QAT)" },
			{ pos: "FW", name: "ALHAYDOS", club: "Al Sadd SC (QAT)" },
			{ pos: "FW", name: "AFIF", club: "Al Sadd SC (QAT)" },
			{ pos: "MF", name: "KARIM", club: "Al Duhail SC (QAT)" },
			{ pos: "DF", name: "AYOUB", club: "Al Gharafa SC (QAT)" },
			{ pos: "DF", name: "HOMAM", club: "Cultural Leonesa (ESP)" },
			{ pos: "FW", name: "YUSUF", club: "Al Wakrah SC (QAT)" },
			{ pos: "DF", name: "KHOUKHI", club: "Al Sadd SC (QAT)" },
			{ pos: "MF", name: "A. ALGANEHI", club: "Al Gharafa SC (QAT)" },
			{ pos: "DF", name: "SULTAN", club: "Al Duhail SC (QAT)" },
			{ pos: "FW", name: "ALMOEZ", club: "Al Duhail SC (QAT)" },
			{ pos: "MF", name: "A. FATHY", club: "Al Arabi SC (QAT)" },
			{ pos: "GK", name: "SALAH", club: "Al Duhail SC (QAT)" },
			{ pos: "GK", name: "BARSHAM", club: "Al Sadd SC (QAT)" },
			{ pos: "MF", name: "MADIBO", club: "Al Wakrah SC (QAT)" },
			{ pos: "FW", name: "TAHSIN", club: "Al Duhail SC (QAT)" },
			{ pos: "DF", name: "ALHASHMI", club: "Al Arabi SC (QAT)" },
			{ pos: "FW", name: "MANAI", club: "Al Shamal SC (QAT)" },
		],
		BIH: [
			{ pos: "GK", name: "VASILJ", club: "FC St. Pauli (GER)" },
			{ pos: "DF", name: "MUJAKIĆ", club: "Gaziantep FK (TUR)" },
			{ pos: "DF", name: "HADŽIKADUNIĆ", club: "UC Sampdoria (ITA)" },
			{ pos: "DF", name: "MUHAREMOVIĆ", club: "US Sassuolo (ITA)" },
			{ pos: "DF", name: "KOLAŠINAC", club: "Atalanta Bergamo (ITA)" },
			{ pos: "MF", name: "TAHIROVIĆ", club: "Brøndby IF (DEN)" },
			{ pos: "DF", name: "DEDIĆ", club: "SL Ben\u0000ca (POR)" },
			{ pos: "MF", name: "GIGOVIĆ", club: "BSC Young Boys (SUI)" },
			{ pos: "FW", name: "BAŽDAR", club: "Jagiellonia Białystok (POL)" },
			{ pos: "FW", name: "DEMIROVIĆ", club: "VfB Stuttgart (GER)" },
			{ pos: "FW", name: "DŽEKO", club: "FC Schalke 04 (GER)" },
			{ pos: "GK", name: "JURKAS", club: "FK Borac Banja Luka (BIH)" },
			{ pos: "MF", name: "BAŠIĆ", club: "FC Astana (KAZ)" },
			{ pos: "MF", name: "ŠUNJIĆ", club: "Pafos FC (CYP)" },
			{ pos: "MF", name: "MEMIĆ", club: "FC Viktoria Plzeň (CZE)" },
			{ pos: "MF", name: "HADŽIAHMETOVIĆ", club: "Hull City FC (ENG)" },
			{ pos: "MF", name: "BURNIĆ", club: "Karlsruher SC (GER)" },
			{ pos: "DF", name: "KATIĆ", club: "FC Schalke 04 (GER)" },
			{ pos: "FW", name: "ALAJBEGOVIĆ", club: "FC Red Bull Salzburg (AUT)" },
			{ pos: "FW", name: "BAJRAKTAREVIĆ", club: "PSV Eindhoven (NED)" },
			{ pos: "DF", name: "RADELJIĆ", club: "HNK Rijeka (CRO)" },
			{ pos: "GK", name: "ZLOMISLIĆ", club: "HNK Rijeka (CRO)" },
			{ pos: "FW", name: "TABAKOVIĆ", club: "Borussia Mönchengladbach (GER)" },
			{ pos: "DF", name: "ČELIK", club: "RC Lens (FRA)" },
			{ pos: "FW", name: "LUKIĆ", club: "Universitatea Cluj (ROU)" },
			{ pos: "MF", name: "MAHMIĆ", club: "FC Slovan Liberec (CZE)" },
		],
		BRA: [
			{ pos: "GK", name: "A. BECKER", club: "Liverpool FC (ENG)" },
			{ pos: "DF", name: "WESLEY", club: "AS Roma (ITA)" },
			{ pos: "DF", name: "GABRIEL", club: "Arsenal FC (ENG)" },
			{ pos: "DF", name: "MARQUINHOS", club: "Paris Saint-Germain (FRA)" },
			{ pos: "MF", name: "CASEMIRO", club: "Manchester United FC (ENG)" },
			{ pos: "DF", name: "ALEX SANDRO", club: "CR Flamengo (BRA)" },
			{ pos: "FW", name: "VINI JR.", club: "Real Madrid C. F. (ESP)" },
			{ pos: "MF", name: "BRUNO G.", club: "Newcastle United FC (ENG)" },
			{ pos: "FW", name: "CUNHA", club: "Manchester United FC (ENG)" },
			{ pos: "FW", name: "NEYMAR JR", club: "Santos FC (BRA)" },
			{ pos: "FW", name: "RAPHINHA", club: "FC Barcelona (ESP)" },
			{ pos: "GK", name: "WEVERTON", club: "Grêmio FBPA (BRA)" },
			{ pos: "DF", name: "DANILO", club: "CR Flamengo (BRA)" },
			{ pos: "DF", name: "BREMER", club: "Juventus FC (ITA)" },
			{ pos: "DF", name: "LEO PEREIRA", club: "CR Flamengo (BRA)" },
			{
				pos: "DF",
				name: "DOUGLAS SANTOS",
				club: "FC Zenit St. Petersburg (RUS)",
			},
			{ pos: "MF", name: "FABINHO", club: "Al Ittihad (KSA)" },
			{ pos: "MF", name: "DANILO S.", club: "Botafogo (BRA)" },
			{ pos: "FW", name: "ENDRICK", club: "Olympique Lyonnais (FRA)" },
			{ pos: "MF", name: "L. PAQUETA", club: "CR Flamengo (BRA)" },
			{ pos: "FW", name: "L. HENRIQUE", club: "FC Zenit St. Petersburg (RUS)" },
			{ pos: "FW", name: "MARTINELLI", club: "Arsenal FC (ENG)" },
			{ pos: "GK", name: "EDERSON", club: "Fenerbahçe SK (TUR)" },
			{ pos: "DF", name: "IBAÑEZ", club: "Al Ahli FC (KSA)" },
			{ pos: "FW", name: "THIAGO", club: "Brentford FC (ENG)" },
			{ pos: "FW", name: "RAYAN", club: "AFC Bournemouth (ENG)" },
		],
		MAR: [
			{ pos: "GK", name: "BONO", club: "Al Hilal SC (KSA)" },
			{ pos: "DF", name: "HAKIMI", club: "Paris Saint-Germain (FRA)" },
			{ pos: "DF", name: "MAZRAOUI", club: "Manchester United FC (ENG)" },
			{ pos: "MF", name: "AMRABAT", club: "Real Betis (ESP)" },
			{ pos: "DF", name: "AGUERD", club: "Olympique Marseille (FRA)" },
			{ pos: "MF", name: "BOUADDI", club: "Lille OSC (FRA)" },
			{ pos: "MF", name: "TALBI", club: "Sunderland AFC (ENG)" },
			{ pos: "MF", name: "OUNAHI", club: "Girona FC (ESP)" },
			{ pos: "FW", name: "RAHIMI", club: "Al Ain FC (UAE)" },
			{ pos: "FW", name: "BRAHIM", club: "Real Madrid C. F. (ESP)" },
			{ pos: "MF", name: "SAIBARI", club: "PSV Eindhoven (NED)" },
			{ pos: "GK", name: "EL KAJOUI", club: "RS Berkane (MAR)" },
			{ pos: "DF", name: "EL OUAHDI", club: "KRC Genk (BEL)" },
			{ pos: "DF", name: "ISSA", club: "Fulham FC (ENG)" },
			{ pos: "MF", name: "EL MOURABET", club: "RC Strasbourg (FRA)" },
			{ pos: "MF", name: "YASSINE", club: "RC Strasbourg (FRA)" },
			{ pos: "FW", name: "EZZALZOULI", club: "Real Betis (ESP)" },
			{ pos: "DF", name: "RIAD", club: "Crystal Palace FC (ENG)" },
			{ pos: "DF", name: "BELAMM ARI", club: "Al Ahly FC (EGY)" },
			{ pos: "FW", name: "EL KAABI", club: "Olympiacos FC (GRE)" },
			{ pos: "FW", name: "AMAIMOUNI", club: "Eintracht Frankfurt (GER)" },
			{ pos: "GK", name: "TAGNAOUTI", club: "ASFAR (MAR)" },
			{ pos: "MF", name: "EL KHANNOUSS", club: "VfB Stuttgart (GER)" },
			{ pos: "MF", name: "EL AYNAOUI", club: "AS Roma (ITA)" },
			{ pos: "DF", name: "HALHAL", club: "KV Mechelen (BEL)" },
			{ pos: "DF", name: "SALAH-EDDINE", club: "PSV Eindhoven (NED)" },
		],
		SCO: [
			{ pos: "GK", name: "GUNN", club: "Nottingham Forest FC (ENG)" },
			{ pos: "DF", name: "HICKEY", club: "Brentford FC (ENG)" },
			{ pos: "DF", name: "ROBERTSON", club: "Liverpool FC (ENG)" },
			{ pos: "MF", name: "MCTOMINAY", club: "SSC Napoli (ITA)" },
			{ pos: "DF", name: "HANLEY", club: "Hibernian FC (SCO)" },
			{ pos: "DF", name: "TIERNEY", club: "Celtic FC (SCO)" },
			{ pos: "MF", name: "MCGINN", club: "Aston Villa FC (ENG)" },
			{ pos: "MF", name: "FLETCHER", club: "Manchester United FC (ENG)" },
			{ pos: "FW", name: "DYKES", club: "Charlton Athletic FC (ENG)" },
			{ pos: "FW", name: "ADAMS", club: "Torino FC (ITA)" },
			{ pos: "MF", name: "CHRISTIE", club: "AFC Bournemouth (ENG)" },
			{ pos: "GK", name: "KELLY", club: "Rangers FC (SCO)" },
			{ pos: "DF", name: "HENDRY", club: "Al Ettifaq FC (KSA)" },
			{ pos: "FW", name: "STEWART", club: "Southampton FC (ENG)" },
			{ pos: "DF", name: "SOUTTAR", club: "Rangers FC (SCO)" },
			{ pos: "DF", name: "HYAM", club: "Wrexham AFC (WAL)" },
			{ pos: "FW", name: "GANNON DOAK", club: "AFC Bournemouth (ENG)" },
			{ pos: "FW", name: "HIRST", club: "Ipswich Town FC (ENG)" },
			{ pos: "MF", name: "FERGUSON", club: "Bologna FC (ITA)" },
			{ pos: "FW", name: "SHANKLAND", club: "Heart Of Midlothian FC (SCO)" },
			{ pos: "GK", name: "GORDON", club: "Heart Of Midlothian FC (SCO)" },
			{ pos: "DF", name: "PATTERSON", club: "Everton FC (ENG)" },
			{ pos: "MF", name: "MCLEAN", club: "Norwich City FC (ENG)" },
			{ pos: "DF", name: "RALSTON", club: "Celtic FC (SCO)" },
			{ pos: "FW", name: "CURTIS", club: "Kilmarnock FC (SCO)" },
			{ pos: "DF", name: "MCKENNA", club: "GNK Dinamo Zagreb (CRO)" },
		],
		HAI: [
			{ pos: "GK", name: "PLACIDE", club: "SC Bastia (FRA)" },
			{ pos: "DF", name: "ARCUS", club: "Angers SCO (FRA)" },
			{ pos: "DF", name: "THERMONCY", club: "BSC Young Boys (SUI)" },
			{ pos: "DF", name: "ADE", club: "LDU Quito (ECU)" },
			{ pos: "DF", name: "DELCROIX", club: "FC Lugano (SUI)" },
			{ pos: "MF", name: "SAINTE", club: "El Paso Locomotive FC (USA)" },
			{ pos: "FW", name: "ETIENNE JR", club: "Toronto FC (CAN)" },
			{ pos: "DF", name: "EXPERIENCE", club: "AS Nancy (FRA)" },
			{ pos: "FW", name: "NAZON", club: "Esteghlal Tehran FC (IRN)" },
			{
				pos: "MF",
				name: "BELLEGARDE",
				club: "Wolverhampton Wanderers FC (ENG)",
			},
			{ pos: "FW", name: "DEEDSON", club: "FC Dallas (USA)" },
			{ pos: "GK", name: "A. PIERRE", club: "FC Sochaux-Montbéliard (FRA)" },
			{
				pos: "DF",
				name: "LACROIX",
				club: "Colorado Springs Switchbacks FC (USA)",
			},
			{ pos: "MF", name: "L. PIERRE", club: "FC Vizela (POR)" },
			{ pos: "FW", name: "PROVIDENCE", club: "Almere City FC (NED)" },
			{ pos: "FW", name: "JOSEPH", club: "Ferencvárosi TC (HUN)" },
			{ pos: "MF", name: "JEAN JACQUES", club: "Philadelphia Union (USA)" },
			{ pos: "FW", name: "ISIDOR", club: "Sunderland AFC (ENG)" },
			{ pos: "FW", name: "FORTUNE", club: "FC Vizela (POR)" },
			{ pos: "FW", name: "PIERROT", club: "Çaykur Rizespor (TUR)" },
			{ pos: "FW", name: "CASIMIR", club: "AJ Auxerre (FRA)" },
			{ pos: "DF", name: "DUVERNE", club: "KAA Gent (BEL)" },
			{ pos: "GK", name: "DUVERGER", club: "FC Cosmos Koblenz (GER)" },
			{ pos: "DF", name: "PAUGIN", club: "SV Zulte Waregem (BEL)" },
			{ pos: "MF", name: "SIMON", club: "FC Tatran Prešov (SVK)" },
			{ pos: "MF", name: "W. PIERRE", club: "Violette AC (HAI)" },
		],
		USA: [
			{ pos: "GK", name: "TURNER", club: "New England Revolution (USA)" },
			{ pos: "DF", name: "DEST", club: "PSV Eindhoven (NED)" },
			{ pos: "DF", name: "RICHARDS", club: "Crystal Palace FC (ENG)" },
			{ pos: "MF", name: "ADAMS", club: "AFC Bournemouth (ENG)" },
			{ pos: "DF", name: "A. ROBINSON", club: "Fulham FC (ENG)" },
			{ pos: "DF", name: "TRUSTY", club: "Celtic FC (SCO)" },
			{ pos: "MF", name: "REYNA", club: "Borussia Mönchengladbach (GER)" },
			{ pos: "MF", name: "MCKENNIE", club: "Juventus FC (ITA)" },
			{ pos: "FW", name: "PEPI", club: "PSV Eindhoven (NED)" },
			{ pos: "FW", name: "PULISIC", club: "AC Milan (ITA)" },
			{ pos: "FW", name: "AARONSON", club: "Leeds United FC (ENG)" },
			{ pos: "DF", name: "M. ROBINSON", club: "FC Cincinnatti (USA)" },
			{ pos: "DF", name: "REAM", club: "Charlotte FC (USA)" },
			{ pos: "MF", name: "BERHALTER", club: "Vancouver Whitecaps FC (CAN)" },
			{ pos: "MF", name: "ROLDAN", club: "Seattle Sounders FC (USA)" },
			{ pos: "DF", name: "FREEMAN", club: "Villarreal CF (ESP)" },
			{ pos: "MF", name: "TILLMAN", club: "Bayer Leverkusen (GER)" },
			{ pos: "DF", name: "ARFSTEN", club: "Columbus Crew (USA)" },
			{ pos: "FW", name: "WRIGHT", club: "Coventry City FC (ENG)" },
			{ pos: "FW", name: "BALOGUN", club: "AS Monaco (FRA)" },
			{ pos: "FW", name: "WEAH", club: "Olympique Marseille (FRA)" },
			{ pos: "DF", name: "MCKENZIE", club: "Toulouse FC (FRA)" },
			{ pos: "DF", name: "SCALLY", club: "Borussia Mönchengladbach (GER)" },
			{ pos: "GK", name: "FREESE", club: "New York City FC (USA)" },
			{ pos: "GK", name: "BRADY", club: "Chicago Fire FC (USA)" },
			{ pos: "FW", name: "ZENDEJAS", club: "Club América (MEX)" },
		],
		AUS: [
			{ pos: "GK", name: "RYAN", club: "Levante UD (ESP)" },
			{ pos: "DF", name: "DEGENEK", club: "APOEL FC (CYP)" },
			{ pos: "DF", name: "CIRCATI", club: "Parma (ITA)" },
			{ pos: "DF", name: "ITALIANO", club: "Grazer AK (AUT)" },
			{ pos: "DF", name: "BOS", club: "Feyenoord Rotterdam (NED)" },
			{ pos: "DF", name: "GERIA", club: "Albirex Niigata (JPN)" },
			{ pos: "FW", name: "LECKIE", club: "Melbourne City FC (AUS)" },
			{ pos: "MF", name: "METCALFE", club: "FC St. Pauli (GER)" },
			{ pos: "FW", name: "TOURE", club: "Norwich City FC (ENG)" },
			{ pos: "FW", name: "HRUSTIC", club: "SC Heracles Almelo (NED)" },
			{ pos: "FW", name: "MABIL", club: "CD Castellón (ESP)" },
			{ pos: "GK", name: "IZZO", club: "Randers FC (DEN)" },
			{ pos: "MF", name: "O'NEILL", club: "New York City FC (USA)" },
			{ pos: "MF", name: "DEVLIN", club: "Heart Of Midlothian FC (SCO)" },
			{ pos: "DF", name: "TREWIN", club: "New York City FC (USA)" },
			{ pos: "DF", name: "BEHICH", club: "Melbourne City FC (AUS)" },
			{ pos: "FW", name: "IRANKUNDA", club: "Watford FC (ENG)" },
			{ pos: "GK", name: "BEACH", club: "Melbourne City FC (AUS)" },
			{ pos: "DF", name: "SOUTTAR", club: "Leicester City FC (ENG)" },
			{ pos: "FW", name: "VOLPATO", club: "US Sassuolo (ITA)" },
			{ pos: "DF", name: "BURGESS", club: "Swansea City AFC (WAL)" },
			{ pos: "MF", name: "IRVINE", club: "FC St. Pauli (GER)" },
			{ pos: "FW", name: "VELUPILLAY", club: "Melbourne Victory FC (AUS)" },
			{ pos: "MF", name: "OKON-ENGSTLER", club: "Sydney FC (AUS)" },
			{ pos: "DF", name: "HERRINGTON", club: "Colorado Rapids (USA)" },
			{ pos: "FW", name: "YENGI", club: "FC Machida Zelvia (JPN)" },
		],
		PAR: [
			{ pos: "GK", name: "FERNANDEZ", club: "Cerro Porteño (PAR)" },
			{ pos: "DF", name: "VELAZQUEZ", club: "Cerro Porteño (PAR)" },
			{ pos: "DF", name: "ALDERETE", club: "Sunderland AFC (ENG)" },
			{ pos: "DF", name: "CACERES", club: "FC Dynamo Moscow (RUS)" },
			{ pos: "DF", name: "BALBUENA", club: "Grêmio FBPA (BRA)" },
			{ pos: "DF", name: "ALONSO", club: "Atlético Mineiro (BRA)" },
			{ pos: "MF", name: "SOSA", club: "SE Palmeiras (BRA)" },
			{ pos: "MF", name: "D. GOMEZ", club: "Brighton & Hove Albion FC (ENG)" },
			{ pos: "FW", name: "SANABRIA", club: "US Cremonese (ITA)" },
			{ pos: "MF", name: "M. ALMIRON", club: "Atlanta United FC (USA)" },
			{ pos: "MF", name: "MAURICIO", club: "SE Palmeiras (BRA)" },
			{ pos: "GK", name: "O. GILL", club: "CA San Lorenzo (ARG)" },
			{ pos: "DF", name: "CANALE", club: "CA Lanús (ARG)" },
			{ pos: "MF", name: "CUBAS", club: "Vancouver Whitecaps FC (CAN)" },
			{ pos: "DF", name: "G. GOMEZ", club: "SE Palmeiras (BRA)" },
			{ pos: "MF", name: "BOBADILLA", club: "São Paulo FC (BRA)" },
			{ pos: "FW", name: "R. GAMARRA", club: "Al Ain FC (UAE)" },
			{ pos: "FW", name: "ARCE", club: "CS Independiente Rivadavia (ARG)" },
			{ pos: "FW", name: "ENCISO", club: "RC Strasbourg (FRA)" },
			{ pos: "MF", name: "OJEDA", club: "Orlando City SC (USA)" },
			{ pos: "FW", name: "AVALOS", club: "CA Independiente (ARG)" },
			{ pos: "GK", name: "OLVEIRA", club: "Club Olimpia (PAR)" },
			{ pos: "MF", name: "GALARZA", club: "Atlanta United FC (USA)" },
			{ pos: "MF", name: "CABALLERO", club: "Portsmouth FC (ENG)" },
			{ pos: "FW", name: "PITTA", club: "Red Bull Bragantino (BRA)" },
			{ pos: "DF", name: "MAIDANA", club: "CA Talleres (ARG)" },
		],
		TUR: [
			{ pos: "GK", name: "MERT", club: "Fenerbahçe SK (TUR)" },
			{ pos: "DF", name: "ZEKİ ÇELİK", club: "AS Roma (ITA)" },
			{ pos: "DF", name: "DEMİRAL", club: "Al Ahli FC (KSA)" },
			{ pos: "DF", name: "ÇAĞLAR", club: "Fenerbahçe SK (TUR)" },
			{ pos: "MF", name: "ÖZCAN", club: "Borussia Dortmund (GER)" },
			{ pos: "MF", name: "ORKUN KÖKÇÜ", club: "Beşiktaş JK (TUR)" },
			{ pos: "FW", name: "AKTÜRKOĞLU", club: "Fenerbahçe SK (TUR)" },
			{ pos: "FW", name: "ARDA GÜLER", club: "Real Madrid C. F. (ESP)" },
			{ pos: "FW", name: "DENİZ GÜL", club: "FC Porto (POR)" },
			{ pos: "MF", name: "ÇALHANOĞLU", club: "FC Internazionale Milano (ITA)" },
			{ pos: "FW", name: "YILDIZ", club: "Juventus FC (ITA)" },
			{ pos: "GK", name: "ALTAY", club: "Manchester United FC (ENG)" },
			{ pos: "DF", name: "EREN ELMALI", club: "Galatasaray SK (TUR)" },
			{ pos: "DF", name: "ABDÜLKERİM", club: "Galatasaray SK (TUR)" },
			{ pos: "DF", name: "OZAN KABAK", club: "TSG Hoffenheim (GER)" },
			{ pos: "MF", name: "İSMAİL", club: "Fenerbahçe SK (TUR)" },
			{ pos: "FW", name: "KAHVECİ", club: "Kasımpaşa SK (TUR)" },
			{ pos: "DF", name: "MERT MÜLDÜR", club: "Fenerbahçe SK (TUR)" },
			{ pos: "FW", name: "YUNUS", club: "Galatasaray SK (TUR)" },
			{
				pos: "DF",
				name: "F. KADIOĞLU",
				club: "Brighton & Hove Albion FC (ENG)",
			},
			{ pos: "FW", name: "BARIŞ", club: "Galatasaray SK (TUR)" },
			{ pos: "MF", name: "KAAN", club: "Galatasaray SK (TUR)" },
			{ pos: "GK", name: "UĞURCAN", club: "Galatasaray SK (TUR)" },
			{ pos: "FW", name: "OĞUZ", club: "Fenerbahçe SK (TUR)" },
			{ pos: "DF", name: "SAMET AKAYDIN", club: "Çaykur Rizespor (TUR)" },
			{ pos: "FW", name: "CAN UZUN", club: "Eintracht Frankfurt (GER)" },
		],
		GER: [
			{ pos: "GK", name: "NEUER", club: "FC Bayern München (GER)" },
			{ pos: "DF", name: "RÜDIGER", club: "Real Madrid C. F. (ESP)" },
			{ pos: "DF", name: "ANTON", club: "Borussia Dortmund (GER)" },
			{ pos: "DF", name: "TAH", club: "FC Bayern München (GER)" },
			{ pos: "MF", name: "PAVLOVIĆ", club: "FC Bayern München (GER)" },
			{ pos: "DF", name: "KIMMICH", club: "FC Bayern München (GER)" },
			{ pos: "FW", name: "HAVERTZ", club: "Arsenal FC (ENG)" },
			{ pos: "MF", name: "GORETZKA", club: "FC Bayern München (GER)" },
			{ pos: "MF", name: "LEWELING", club: "VfB Stuttgart (GER)" },
			{ pos: "MF", name: "MUSIALA", club: "FC Bayern München (GER)" },
			{ pos: "FW", name: "WOLTEMADE", club: "Newcastle United FC (ENG)" },
			{ pos: "GK", name: "BAUMANN", club: "TSG Hoffenheim (GER)" },
			{ pos: "MF", name: "GROß", club: "Brighton & Hove Albion FC (ENG)" },
			{ pos: "FW", name: "BEIER", club: "Borussia Dortmund (GER)" },
			{ pos: "DF", name: "SCHLOTTERBECK", club: "Borussia Dortmund (GER)" },
			{ pos: "MF", name: "STILLER", club: "VfB Stuttgart (GER)" },
			{ pos: "MF", name: "WIRTZ", club: "Liverpool FC (ENG)" },
			{ pos: "DF", name: "BROWN", club: "Eintracht Frankfurt (GER)" },
			{ pos: "MF", name: "SANÉ", club: "Galatasaray SK (TUR)" },
			{ pos: "MF", name: "AMIRI", club: "1. FSV Mainz 05 (GER)" },
			{ pos: "GK", name: "NÜBEL", club: "VfB Stuttgart (GER)" },
			{ pos: "DF", name: "RAUM", club: "RB Leipzig (GER)" },
			{ pos: "MF", name: "NMECHA", club: "Borussia Dortmund (GER)" },
			{ pos: "DF", name: "THIAW", club: "Newcastle United FC (ENG)" },
			{ pos: "MF", name: "KARL", club: "FC Bayern München (GER)" },
			{ pos: "FW", name: "UNDAV", club: "VfB Stuttgart (GER)" },
		],
		ECU: [
			{ pos: "GK", name: "GALINDEZ", club: "CA Huracán (ARG)" },
			{ pos: "DF", name: "TORRES", club: "SC Internacional (BRA)" },
			{ pos: "DF", name: "HINCAPIE", club: "Arsenal FC (ENG)" },
			{ pos: "DF", name: "ORDÓÑEZ", club: "Club Brugge (BEL)" },
			{ pos: "MF", name: "ALCIVAR", club: "Independiente Del Valle (ECU)" },
			{ pos: "DF", name: "PACHO", club: "Paris Saint-Germain (FRA)" },
			{ pos: "DF", name: "ESTUPIÑÁN", club: "AC Milan (ITA)" },
			{ pos: "MF", name: "A. VALENCIA", club: "Royal Antwerp FC (BEL)" },
			{ pos: "FW", name: "YEBOAH ZAMORA", club: "Venezia FC (ITA)" },
			{ pos: "MF", name: "PAEZ", club: "CA River Plate (ARG)" },
			{
				pos: "FW",
				name: "RODRIGUEZ",
				club: "Royale Union Saint-Gilloise (BEL)",
			},
			{ pos: "GK", name: "RAMÍREZ", club: "AE Ki\u0000sia FC (GRE)" },
			{ pos: "FW", name: "E. VALENCIA", club: "CF Pachuca (MEX)" },
			{ pos: "MF", name: "MINDA", club: "Atlético Mineiro (BRA)" },
			{ pos: "MF", name: "VITE", club: "Pumas UNAM (MEX)" },
			{ pos: "FW", name: "J. CAICEDO", club: "CA Huracán (ARG)" },
			{ pos: "DF", name: "PRECIADO", club: "Atlético Mineiro (BRA)" },
			{ pos: "MF", name: "CASTILLO", club: "FC Midtjylland (DEN)" },
			{ pos: "FW", name: "PLATA", club: "CR Flamengo (BRA)" },
			{ pos: "FW", name: "ANGULO", club: "Sunderland AFC (ENG)" },
			{ pos: "MF", name: "FRANCO", club: "Atlético Mineiro (BRA)" },
			{ pos: "GK", name: "VALLE", club: "LDU Quito (ECU)" },
			{ pos: "MF", name: "M. CAICEDO", club: "Chelsea FC (ENG)" },
			{ pos: "FW", name: "AREVALO", club: "VfB Stuttgart (GER)" },
			{ pos: "DF", name: "POROZO", club: "Club Tijuana (MEX)" },
			{ pos: "DF", name: "MEDINA", club: "KRC Genk (BEL)" },
		],
		CIV: [
			{ pos: "GK", name: "Y. FOFANA", club: "Çaykur Rizespor (TUR)" },
			{ pos: "DF", name: "O. DIOMANDE", club: "Sporting CP (POR)" },
			{ pos: "DF", name: "G. KONAN", club: "Gil Vicente FC (POR)" },
			{ pos: "MF", name: "SERI", club: "NK Maribor (SVN)" },
			{ pos: "DF", name: "SINGO", club: "Galatasaray SK (TUR)" },
			{ pos: "MF", name: "FOFANA", club: "FC Porto (POR)" },
			{ pos: "DF", name: "KOSSOUNOU", club: "Atalanta Bergamo (ITA)" },
			{ pos: "MF", name: "KESSIE", club: "Al Ahli FC (KSA)" },
			{ pos: "FW", name: "BONNY", club: "FC Internazionale Milano (ITA)" },
			{ pos: "FW", name: "ADINGRA", club: "AS Monaco (FRA)" },
			{ pos: "FW", name: "YAN DIOMANDE", club: "RB Leipzig (GER)" },
			{ pos: "FW", name: "WAHI", club: "OGC Nice (FRA)" },
			{ pos: "DF", name: "OPERI", club: "Başakşehir FK (TUR)" },
			{ pos: "FW", name: "DIAKITE", club: "Cercle Brugge (BEL)" },
			{ pos: "FW", name: "AMAD", club: "Manchester United FC (ENG)" },
			{ pos: "GK", name: "KONE", club: "Sporting Charleroi (BEL)" },
			{ pos: "DF", name: "G. DOUE", club: "RC Strasbourg (FRA)" },
			{ pos: "MF", name: "SANGARE", club: "Nottingham Forest FC (ENG)" },
			{ pos: "FW", name: "PEPE", club: "Villarreal CF (ESP)" },
			{ pos: "DF", name: "AGBADOU", club: "Beşiktaş JK (TUR)" },
			{ pos: "DF", name: "NDICKA", club: "AS Roma (ITA)" },
			{ pos: "FW", name: "GUESSAND", club: "Crystal Palace FC (ENG)" },
			{ pos: "GK", name: "LAFONT", club: "Panathinaikos FC (GRE)" },
			{ pos: "FW", name: "TOURE", club: "TSG Hoffenheim (GER)" },
			{ pos: "MF", name: "GUIAGON", club: "Sporting Charleroi (BEL)" },
			{ pos: "MF", name: "INAO", club: "Trabzonspor (TUR)" },
		],
		CUW: [
			{ pos: "GK", name: "ROOM", club: "Miami FC (USA)" },
			{ pos: "DF", name: "SAMBO", club: "Sparta Rotterdam (NED)" },
			{ pos: "DF", name: "GAARI", club: "Abha Club (KSA)" },
			{ pos: "DF", name: "VAN EIJMA", club: "RKC Waalwijk (NED)" },
			{ pos: "DF", name: "FLORANUS", club: "PEC Zwolle (NED)" },
			{ pos: "MF", name: "ROEMERATOE", club: "RKC Waalwijk (NED)" },
			{ pos: "MF", name: "J. BACUNA", club: "FC Volendam (NED)" },
			{ pos: "MF", name: "COMENENCIA", club: "FC Zürich (SUI)" },
			{ pos: "FW", name: "LOCADIA", club: "Miami FC (USA)" },
			{ pos: "MF", name: "L. BACUNA", club: "Iğdır FK (TUR)" },
			{ pos: "FW", name: "ANTONISSE", club: "AE Ki\u0000sia FC (GRE)" },
			{ pos: "FW", name: "HANSEN", club: "Middlesbrough FC (ENG)" },
			{ pos: "FW", name: "NOSLIN", club: "SC Telstar (NED)" },
			{ pos: "FW", name: "GORRE", club: "Maccabi Haifa FC (ISR)" },
			{ pos: "MF", name: "MARTHA", club: "Rotherham United FC (ENG)" },
			{ pos: "FW", name: "MARGARITHA", club: "SK Beveren (BEL)" },
			{ pos: "FW", name: "KUWAS", club: "FC Volendam (NED)" },
			{ pos: "DF", name: "OBISPO", club: "PSV Eindhoven (NED)" },
			{ pos: "FW", name: "KASTANEER", club: "Terengganu FC (MAS)" },
			{ pos: "DF", name: "BRENET", club: "Kayserispor (TUR)" },
			{ pos: "MF", name: "CHONG", club: "She\u0000eld United FC (ENG)" },
			{ pos: "MF", name: "FELIDA", club: "FC Den Bosch (NED)" },
			{ pos: "DF", name: "BAZOER", club: "Konyaspor (TUR)" },
			{ pos: "DF", name: "FONVILLE", club: "NEC Nijmegen (NED)" },
			{ pos: "GK", name: "BODAK", club: "SC Telstar (NED)" },
			{ pos: "GK", name: "DOORNBUSCH", club: "VVV Venlo (NED)" },
		],
		NED: [
			{
				pos: "GK",
				name: "VERBRUGGEN",
				club: "Brighton & Hove Albion FC (ENG)",
			},
			{ pos: "DF", name: "J. TIMBER", club: "Arsenal FC (ENG)" },
			{ pos: "MF", name: "DE ROON", club: "Atalanta Bergamo (ITA)" },
			{ pos: "DF", name: "VIRGIL", club: "Liverpool FC (ENG)" },
			{ pos: "DF", name: "AKÉ", club: "Manchester City FC (ENG)" },
			{ pos: "DF", name: "VAN HECKE", club: "Brighton & Hove Albion FC (ENG)" },
			{ pos: "MF", name: "KLUIVERT", club: "AFC Bournemouth (ENG)" },
			{ pos: "MF", name: "GRAVENBERCH", club: "Liverpool FC (ENG)" },
			{ pos: "FW", name: "WEGHORST", club: "AFC Ajax (NED)" },
			{ pos: "FW", name: "MEMPHIS", club: "SC Corinthians (BRA)" },
			{ pos: "FW", name: "GAKPO", club: "Liverpool FC (ENG)" },
			{ pos: "DF", name: "WIEFFER", club: "Brighton & Hove Albion FC (ENG)" },
			{ pos: "GK", name: "ROEFS", club: "Sunderland AFC (ENG)" },
			{ pos: "MF", name: "REIJNDERS", club: "Manchester City FC (ENG)" },
			{ pos: "DF", name: "VAN DE VEN", club: "Tottenham Hotspur FC (ENG)" },
			{ pos: "MF", name: "TIL", club: "PSV Eindhoven (NED)" },
			{ pos: "FW", name: "LANG", club: "Galatasaray SK (TUR)" },
			{ pos: "FW", name: "MALEN", club: "AS Roma (ITA)" },
			{ pos: "FW", name: "BROBBEY", club: "Sunderland AFC (ENG)" },
			{ pos: "MF", name: "KOOPMEINERS", club: "Juventus FC (ITA)" },
			{ pos: "MF", name: "F. DE JONG", club: "FC Barcelona (ESP)" },
			{ pos: "DF", name: "DUMFRIES", club: "FC Internazionale Milano (ITA)" },
			{ pos: "GK", name: "FLEKKEN", club: "Bayer Leverkusen (GER)" },
			{ pos: "FW", name: "SUMMERVILLE", club: "West Ham United FC (ENG)" },
			{ pos: "DF", name: "HATO", club: "Chelsea FC (ENG)" },
			{ pos: "MF", name: "Q. TIMBER", club: "Olympique Marseille (FRA)" },
		],
		JPN: [
			{ pos: "GK", name: "SUZUKI", club: "Parma (ITA)" },
			{ pos: "DF", name: "SUGAWARA", club: "SV Werder Bremen (GER)" },
			{ pos: "DF", name: "TANIGUCHI", club: "Sint-Truiden VV (BEL)" },
			{ pos: "DF", name: "ITAKURA", club: "AFC Ajax (NED)" },
			{ pos: "DF", name: "NAGATOMO", club: "FC Tokyo (JPN)" },
			{ pos: "MF", name: "ENDO", club: "Liverpool FC (ENG)" },
			{ pos: "MF", name: "TANAKA", club: "Leeds United FC (ENG)" },
			{ pos: "MF", name: "KUBO", club: "Real Sociedad (ESP)" },
			{ pos: "FW", name: "GOTO", club: "Sint-Truiden VV (BEL)" },
			{ pos: "MF", name: "DOAN", club: "Eintracht Frankfurt (GER)" },
			{ pos: "MF", name: "DAIZEN", club: "Celtic FC (SCO)" },
			{ pos: "GK", name: "OSAKO", club: "Sanfrecce Hiroshima (JPN)" },
			{ pos: "MF", name: "NAKAMURA", club: "Stade Reims (FRA)" },
			{ pos: "MF", name: "ITO", club: "KRC Genk (BEL)" },
			{ pos: "MF", name: "KAMADA", club: "Crystal Palace FC (ENG)" },
			{ pos: "DF", name: "WATANABE", club: "Feyenoord Rotterdam (NED)" },
			{ pos: "MF", name: "Y. SUZUKI", club: "SC Freiburg (GER)" },
			{ pos: "FW", name: "AYASE", club: "Feyenoord Rotterdam (NED)" },
			{ pos: "FW", name: "OGAWA", club: "NEC Nijmegen (NED)" },
			{ pos: "DF", name: "SEKO", club: "Le Havre AC (FRA)" },
			{ pos: "DF", name: "H. ITO", club: "FC Bayern München (GER)" },
			{ pos: "DF", name: "TOMIYASU", club: "AFC Ajax (NED)" },
			{ pos: "GK", name: "HAYAKAWA", club: "Kashima Antlers (JPN)" },
			{ pos: "MF", name: "SANO", club: "1. FSV Mainz 05 (GER)" },
			{ pos: "DF", name: "J. SUZUKI", club: "FC København (DEN)" },
			{ pos: "FW", name: "SHIOGAI", club: "VfL Wolfsburg (GER)" },
		],
		TUN: [
			{ pos: "GK", name: "CHAMAKH", club: "Club Africain (TUN)" },
			{ pos: "DF", name: "ABDI", club: "OGC Nice (FRA)" },
			{ pos: "DF", name: "TALBI", club: "FC Lorient (FRA)" },
			{ pos: "DF", name: "REKIK", club: "NK Maribor (SVN)" },
			{ pos: "DF", name: "AROUS", club: "Kasımpaşa SK (TUR)" },
			{ pos: "DF", name: "BRONN", club: "Servette FC (SUI)" },
			{ pos: "FW", name: "ACHOURI", club: "FC København (DEN)" },
			{ pos: "FW", name: "SAAD", club: "Hannover 96 (GER)" },
			{ pos: "FW", name: "MASTOURI", club: "FC Dynamo Makhachkala (RUS)" },
			{ pos: "MF", name: "MEJBRI", club: "Burnley FC (ENG)" },
			{ pos: "MF", name: "GHARBI", club: "FC Augsburg (GER)" },
			{ pos: "DF", name: "BEN OUANES", club: "Kasımpaşa SK (TUR)" },
			{ pos: "MF", name: "KHEDIRA", club: "1. FC Union Berlin (GER)" },
			{ pos: "MF", name: "AYARI", club: "Paris Saint-Germain (FRA)" },
			{ pos: "MF", name: "BELHADJ MAHMOUD", club: "FC Lugano (SUI)" },
			{ pos: "GK", name: "DAHMEN", club: "CS Sfaxien (TUN)" },
			{ pos: "MF", name: "SKHIRI", club: "Eintracht Frankfurt (GER)" },
			{ pos: "FW", name: "ELLOUMI", club: "Vancouver Whitecaps FC (CAN)" },
			{ pos: "FW", name: "CHAOUAT", club: "Club Africain (TUN)" },
			{ pos: "DF", name: "VALERY", club: "BSC Young Boys (SUI)" },
			{ pos: "DF", name: "BEN HMIDA", club: "Espérance De Tunisie (TUN)" },
			{ pos: "GK", name: "BEN HSAN", club: "Étoile Du Sahel (TUN)" },
			{ pos: "DF", name: "NEFFATI", club: "IFK Norrköping FK (SWE)" },
			{ pos: "DF", name: "CHIKHAOUI", club: "US Monastir (TUN)" },
			{ pos: "MF", name: "SLIMANE", club: "Norwich City FC (ENG)" },
			{ pos: "MF", name: "TOUNEKTI", club: "Celtic FC (SCO)" },
		],
		SWE: [
			{ pos: "GK", name: "ZETTERSTRÖM", club: "Derby County FC (ENG)" },
			{ pos: "DF", name: "LAGERBIELKE", club: "SC Braga (POR)" },
			{ pos: "DF", name: "LINDELÖF", club: "Aston Villa FC (ENG)" },
			{ pos: "DF", name: "HIEN", club: "Atalanta Bergamo (ITA)" },
			{ pos: "DF", name: "GUDMUNDSSON", club: "Leeds United FC (ENG)" },
			{ pos: "DF", name: "H. JOHANSSON", club: "FC Dallas (USA)" },
			{ pos: "MF", name: "BERGVALL", club: "Tottenham Hotspur FC (ENG)" },
			{ pos: "DF", name: "SVENSSON", club: "Borussia Dortmund (GER)" },
			{ pos: "FW", name: "ISAK", club: "Liverpool FC (ENG)" },
			{ pos: "MF", name: "NYGREN", club: "Celtic FC (SCO)" },
			{ pos: "FW", name: "ELANGA", club: "Newcastle United FC (ENG)" },
			{ pos: "GK", name: "V. JOHANSSON", club: "Stoke City FC (ENG)" },
			{ pos: "MF", name: "SEMA", club: "Pafos FC (CYP)" },
			{ pos: "DF", name: "EKDAL", club: "Burnley FC (ENG)" },
			{ pos: "DF", name: "STARFELT", club: "RC Celta Vigo (ESP)" },
			{ pos: "MF", name: "KARLSTRÖM", club: "Udinese (ITA)" },
			{ pos: "FW", name: "GYÖKERES", club: "Arsenal FC (ENG)" },
			{ pos: "MF", name: "AYARI", club: "Brighton & Hove Albion FC (ENG)" },
			{ pos: "MF", name: "SVANBERG", club: "VfL Wolfsburg (GER)" },
			{ pos: "DF", name: "SMITH", club: "FC St. Pauli (GER)" },
			{ pos: "DF", name: "BERNHARDSSON", club: "Holstein Kiel (GER)" },
			{ pos: "MF", name: "ZENELI", club: "Royale Union Saint-Gilloise (BEL)" },
			{ pos: "GK", name: "NORDFELDT", club: "AIK Stockholm (SWE)" },
			{ pos: "DF", name: "STROUD", club: "Mjällby AIF (SWE)" },
			{ pos: "FW", name: "NILSSON", club: "Club Brugge (BEL)" },
			{ pos: "FW", name: "ALI", club: "Malmö FF (SWE)" },
		],
		BEL: [
			{ pos: "GK", name: "COURTOIS", club: "Real Madrid C. F. (ESP)" },
			{ pos: "DF", name: "DEBAST", club: "Sporting CP (POR)" },
			{ pos: "DF", name: "THEATE", club: "Eintracht Frankfurt (GER)" },
			{ pos: "DF", name: "MECHELE", club: "Club Brugge (BEL)" },
			{ pos: "DF", name: "DE CUYPER", club: "Brighton & Hove Albion FC (ENG)" },
			{ pos: "MF", name: "WITSEL", club: "Girona FC (ESP)" },
			{ pos: "MF", name: "DE BRUYNE", club: "SSC Napoli (ITA)" },
			{ pos: "MF", name: "TIELEMANS", club: "Aston Villa FC (ENG)" },
			{ pos: "FW", name: "LUKAKU", club: "SSC Napoli (ITA)" },
			{ pos: "FW", name: "TROSSARD", club: "Arsenal FC (ENG)" },
			{ pos: "FW", name: "DOKU", club: "Manchester City FC (ENG)" },
			{ pos: "GK", name: "LAMMENS", club: "Manchester United FC (ENG)" },
			{ pos: "GK", name: "PENDERS", club: "RC Strasbourg (FRA)" },
			{ pos: "FW", name: "LUKEBAKIO", club: "SL Ben\u0000ca (POR)" },
			{ pos: "DF", name: "MEUNIER", club: "Lille OSC (FRA)" },
			{ pos: "DF", name: "DE WINTER", club: "AC Milan (ITA)" },
			{ pos: "FW", name: "DE KETELAERE", club: "Atalanta Bergamo (ITA)" },
			{ pos: "DF", name: "SEYS", club: "Club Brugge (BEL)" },
			{ pos: "MF", name: "MOREIRA", club: "RC Strasbourg (FRA)" },
			{ pos: "MF", name: "VANAKEN", club: "Club Brugge (BEL)" },
			{ pos: "DF", name: "CASTAGNE", club: "Fulham FC (ENG)" },
			{ pos: "MF", name: "SAELEMAEKERS", club: "AC Milan (ITA)" },
			{ pos: "MF", name: "RASKIN", club: "Rangers FC (SCO)" },
			{ pos: "MF", name: "ONANA", club: "Aston Villa FC (ENG)" },
			{ pos: "DF", name: "NGOY", club: "Lille OSC (FRA)" },
			{ pos: "FW", name: "FERNANDEZ-PARDO", club: "Lille OSC (FRA)" },
		],
		IRN: [
			{ pos: "GK", name: "BEIRANVAND", club: "Tractor Sazi Tabriz FC (IRN)" },
			{ pos: "DF", name: "SALEH", club: "Esteghlal Tehran FC (IRN)" },
			{ pos: "DF", name: "E. HAJISAFI", club: "Sepahan SC (IRN)" },
			{ pos: "DF", name: "SHOJA", club: "Tractor Sazi Tabriz FC (IRN)" },
			{ pos: "DF", name: "M. MOHAMM ADI", club: "Persepolis FC (IRN)" },
			{ pos: "MF", name: "S. EZATOLAHI", club: "Shabab Al Ahli Club (UAE)" },
			{ pos: "MF", name: "A. JAHANBAKHSH", club: "FCV Dender EH (BEL)" },
			{ pos: "MF", name: "M. MOHEBBI", club: "FC Rostov (RUS)" },
			{ pos: "FW", name: "TAREMI", club: "Olympiacos FC (GRE)" },
			{ pos: "FW", name: "MEHDI GHAYEDI", club: "Al Nasr SC (UAE)" },
			{ pos: "FW", name: "A. ALIPOUR", club: "Persepolis FC (IRN)" },
			{ pos: "GK", name: "PAYAM", club: "Persepolis FC (IRN)" },
			{ pos: "DF", name: "KANANI", club: "Persepolis FC (IRN)" },
			{ pos: "MF", name: "GHODDOS", club: "Al Ittihad Kalba SCC (UAE)" },
			{ pos: "MF", name: "ROOZBEH", club: "Esteghlal Tehran FC (IRN)" },
			{ pos: "MF", name: "M. TORABI", club: "Tractor Sazi Tabriz FC (IRN)" },
			{ pos: "DF", name: "ARYA", club: "Sepahan SC (IRN)" },
			{ pos: "FW", name: "AMIRHOSSEIN", club: "Tractor Sazi Tabriz FC (IRN)" },
			{ pos: "DF", name: "ALI", club: "Foolad Khuzestan FC (IRN)" },
			{ pos: "FW", name: "SHAHRIYAR", club: "Al Ittihad Kalba SCC (UAE)" },
			{ pos: "MF", name: "MOHAMM AD", club: "Al Wahda SC (UAE)" },
			{ pos: "GK", name: "HOSSEINI", club: "Sepahan SC (IRN)" },
			{ pos: "DF", name: "RAMIN", club: "Foolad Khuzestan FC (IRN)" },
			{ pos: "FW", name: "DARGAHI", club: "Standard Liège (BEL)" },
			{ pos: "DF", name: "DANIAL", club: "Malavan Anzali FC (IRN)" },
			{ pos: "MF", name: "RAZAGH", club: "Esteghlal Tehran FC (IRN)" },
		],
		EGY: [
			{ pos: "GK", name: "M. ELSHENAWY", club: "Al Ahly FC (EGY)" },
			{ pos: "DF", name: "YASSER", club: "Al Ahly FC (EGY)" },
			{ pos: "DF", name: "M. HANY", club: "Al Ahly FC (EGY)" },
			{ pos: "DF", name: "HOSSAM", club: "Zamalek SC (EGY)" },
			{ pos: "DF", name: "R. RABIAA", club: "Al Ain FC (UAE)" },
			{ pos: "DF", name: "M. ABDELMONIEM", club: "OGC Nice (FRA)" },
			{ pos: "FW", name: "M. TREZEGUET", club: "Al Ahly FC (EGY)" },
			{ pos: "MF", name: "E. ASHOUR", club: "Al Ahly FC (EGY)" },
			{ pos: "FW", name: "ABDELKARIM", club: "FC Barcelona (ESP)" },
			{ pos: "FW", name: "M. SALAH", club: "Liverpool FC (ENG)" },
			{ pos: "MF", name: "ZICO", club: "Pyramids FC (EGY)" },
			{ pos: "FW", name: "H. HASSAN", club: "Real Oviedo (ESP)" },
			{ pos: "DF", name: "A. FATOUH", club: "Zamalek SC (EGY)" },
			{ pos: "MF", name: "H. FATHY", club: "Al Wakrah SC (QAT)" },
			{ pos: "DF", name: "K. HAFEZ", club: "Pyramids FC (EGY)" },
			{ pos: "GK", name: "M. SOLIMAN", club: "Zamalek SC (EGY)" },
			{ pos: "MF", name: "M. LASHIN", club: "Pyramids FC (EGY)" },
			{ pos: "MF", name: "DONGA", club: "Al Najmah SC (KSA)" },
			{ pos: "MF", name: "M. ATTIA", club: "Al Ahly FC (EGY)" },
			{ pos: "FW", name: "I. ADEL", club: "FC Nordsjælland (DEN)" },
			{ pos: "MF", name: "M. SABER", club: "ZED FC (EGY)" },
			{ pos: "FW", name: "MARMOUSH", club: "Manchester City FC (ENG)" },
			{ pos: "GK", name: "SHOUBIR", club: "Al Ahly FC (EGY)" },
			{ pos: "DF", name: "T. ALAA", club: "ZED FC (EGY)" },
			{ pos: "FW", name: "ZIZO", club: "Al Ahly FC (EGY)" },
			{ pos: "GK", name: "M. ALAA", club: "El Gouna FC (EGY)" },
		],
		NZL: [
			{ pos: "GK", name: "CROCOMBE", club: "Millwall FC (ENG)" },
			{ pos: "DF", name: "PAYNE", club: "Wellington Phoenix FC (NZL)" },
			{ pos: "DF", name: "DE VRIES", club: "Auckland FC (NZL)" },
			{ pos: "DF", name: "BINDON", club: "She\u0000eld United FC (ENG)" },
			{ pos: "DF", name: "BOXALL", club: "Minnesota United FC (USA)" },
			{ pos: "MF", name: "BELL", club: "Viking Stavanger (NOR)" },
			{ pos: "MF", name: "GARBETT", club: "Peterborough United FC (ENG)" },
			{ pos: "MF", name: "STAMENIC", club: "Swansea City AFC (WAL)" },
			{ pos: "FW", name: "WOOD", club: "Nottingham Forest FC (ENG)" },
			{ pos: "MF", name: "SINGH", club: "Wellington Phoenix FC (NZL)" },
			{ pos: "MF", name: "JUST", club: "Motherwell FC (SCO)" },
			{ pos: "GK", name: "PAULSEN", club: "Lechia Gdańsk (POL)" },
			{ pos: "DF", name: "CACACE", club: "Wrexham AFC (WAL)" },
			{ pos: "MF", name: "RUFER", club: "Wellington Phoenix FC (NZL)" },
			{ pos: "DF", name: "PIJNAKER", club: "Auckland FC (NZL)" },
			{ pos: "DF", name: "SURMAN", club: "Portland Timbers (USA)" },
			{ pos: "FW", name: "BARBAROUSES", club: "WS Wanderers FC (AUS)" },
			{ pos: "FW", name: "WAINE", club: "Port Vale FC (ENG)" },
			{ pos: "MF", name: "OLD", club: "AS Saint-Etienne (FRA)" },
			{ pos: "MF", name: "MCCOWATT", club: "Silkeborg IF (DEN)" },
			{ pos: "FW", name: "RANDALL", club: "Auckland FC (NZL)" },
			{ pos: "GK", name: "WOUD", club: "Auckland FC (NZL)" },
			{ pos: "MF", name: "THOMAS", club: "PEC Zwolle (NED)" },
			{ pos: "DF", name: "ELLIOT", club: "Auckland FC (NZL)" },
			{ pos: "MF", name: "BAYLISS", club: "Newcastle United Jets FC (AUS)" },
			{ pos: "DF", name: "SMITH", club: "Braintree Town FC (ENG)" },
		],
		ESP: [
			{ pos: "GK", name: "RAYA", club: "Arsenal FC (ENG)" },
			{ pos: "DF", name: "MARC PUBILL", club: "Atlético De Madrid (ESP)" },
			{ pos: "DF", name: "GRIMALDO", club: "Bayer Leverkusen (GER)" },
			{ pos: "DF", name: "ERIC", club: "FC Barcelona (ESP)" },
			{ pos: "DF", name: "M. LLORENTE", club: "Atlético De Madrid (ESP)" },
			{ pos: "MF", name: "MERINO", club: "Arsenal FC (ENG)" },
			{ pos: "FW", name: "FERRAN", club: "FC Barcelona (ESP)" },
			{ pos: "MF", name: "FABIÁN", club: "Paris Saint-Germain (FRA)" },
			{ pos: "MF", name: "GAVI", club: "FC Barcelona (ESP)" },
			{ pos: "FW", name: "OLMO", club: "FC Barcelona (ESP)" },
			{ pos: "FW", name: "YEREMY", club: "Crystal Palace FC (ENG)" },
			{ pos: "DF", name: "PEDRO PORRO", club: "Tottenham Hotspur FC (ENG)" },
			{ pos: "GK", name: "JOAN GARCIA", club: "FC Barcelona (ESP)" },
			{ pos: "DF", name: "LAPORTE", club: "Athletic Club (ESP)" },
			{ pos: "MF", name: "ALEX B.", club: "Atlético De Madrid (ESP)" },
			{ pos: "MF", name: "RODRIGO", club: "Manchester City FC (ENG)" },
			{ pos: "FW", name: "WILLIAMS JR", club: "Athletic Club (ESP)" },
			{ pos: "MF", name: "ZUBIMENDI", club: "Arsenal FC (ENG)" },
			{ pos: "FW", name: "LAMINE YAMAL", club: "FC Barcelona (ESP)" },
			{ pos: "MF", name: "PEDRI", club: "FC Barcelona (ESP)" },
			{ pos: "FW", name: "OYARZABAL", club: "Real Sociedad (ESP)" },
			{ pos: "DF", name: "CUBARSÍ", club: "FC Barcelona (ESP)" },
			{ pos: "GK", name: "UNAI SIMÓN", club: "Athletic Club (ESP)" },
			{ pos: "DF", name: "CUCURELLA", club: "Chelsea FC (ENG)" },
			{ pos: "FW", name: "VICTOR M.V.", club: "CA Osasuna (ESP)" },
			{ pos: "FW", name: "B. IGLESIAS", club: "RC Celta Vigo (ESP)" },
		],
		URU: [
			{ pos: "GK", name: "S. ROCHET", club: "SC Internacional (BRA)" },
			{ pos: "DF", name: "J.M. GIMÉNEZ", club: "Atlético De Madrid (ESP)" },
			{ pos: "DF", name: "S. CACERES", club: "Club América (MEX)" },
			{ pos: "DF", name: "R. ARAUJO", club: "FC Barcelona (ESP)" },
			{ pos: "MF", name: "M. UGARTE", club: "Manchester United FC (ENG)" },
			{ pos: "MF", name: "R. BENTANCUR", club: "Tottenham Hotspur FC (ENG)" },
			{ pos: "MF", name: "N. DE LA CRUZ", club: "CR Flamengo (BRA)" },
			{ pos: "MF", name: "F. VALVERDE", club: "Real Madrid C. F. (ESP)" },
			{ pos: "FW", name: "D. NUÑEZ", club: "Al Hilal SC (KSA)" },
			{ pos: "MF", name: "G. DE ARRASCAETA", club: "CR Flamengo (BRA)" },
			{ pos: "FW", name: "F. PELLISTRI", club: "Panathinaikos FC (GRE)" },
			{ pos: "GK", name: "S. MELE", club: "CF Monterrey (MEX)" },
			{ pos: "DF", name: "G. VARELA", club: "CR Flamengo (BRA)" },
			{ pos: "MF", name: "A. CANOBBIO", club: "Fluminense FC (BRA)" },
			{ pos: "MF", name: "E. MARTINEZ", club: "SE Palmeiras (BRA)" },
			{ pos: "DF", name: "M. OLIVERA", club: "SSC Napoli (ITA)" },
			{ pos: "DF", name: "M. VIÑA", club: "CA River Plate (ARG)" },
			{ pos: "FW", name: "B. RODRIGUEZ", club: "Club América (MEX)" },
			{ pos: "FW", name: "R. AGUIRRE", club: "Tigres UANL (MEX)" },
			{ pos: "MF", name: "M. ARAUJO", club: "Sporting CP (POR)" },
			{ pos: "FW", name: "F. VIÑAS", club: "Real Oviedo (ESP)" },
			{ pos: "MF", name: "J. PIQUEREZ", club: "SE Palmeiras (BRA)" },
			{ pos: "GK", name: "F. MUSLERA", club: "Estudiantes LP (ARG)" },
			{ pos: "DF", name: "S. BUENO", club: "Wolverhampton Wanderers FC (ENG)" },
			{ pos: "MF", name: "J.M. SANABRIA", club: "Real Salt Lake (USA)" },
			{ pos: "MF", name: "R. ZALAZAR", club: "SC Braga (POR)" },
		],
		KSA: [
			{ pos: "GK", name: "ALAQIDI", club: "Al Nassr FC (KSA)" },
			{ pos: "DF", name: "MAJRASHI", club: "Al Ahli FC (KSA)" },
			{ pos: "DF", name: "LAJAMI", club: "Al Hilal SC (KSA)" },
			{ pos: "DF", name: "ALAMRI", club: "Al Nassr FC (KSA)" },
			{ pos: "DF", name: "ALTAMBAKTI", club: "Al Hilal SC (KSA)" },
			{ pos: "MF", name: "NASSER", club: "Al Hilal SC (KSA)" },
			{ pos: "MF", name: "MUSAB", club: "Al Qadsiah FC (KSA)" },
			{ pos: "FW", name: "AIMAN", club: "Al Nassr FC (KSA)" },
			{ pos: "FW", name: "FERAS", club: "Al Ahli FC (KSA)" },
			{ pos: "FW", name: "SALEM", club: "Al Hilal SC (KSA)" },
			{ pos: "FW", name: "ALSHEHRI", club: "Al Ittihad (KSA)" },
			{ pos: "DF", name: "SAUD", club: "RC Lens (FRA)" },
			{ pos: "DF", name: "NAWAF", club: "Al Nassr FC (KSA)" },
			{ pos: "DF", name: "KADISH", club: "Al Ittihad (KSA)" },
			{ pos: "MF", name: "ALKHAIBARI", club: "Al Nassr FC (KSA)" },
			{ pos: "MF", name: "ZIYAD", club: "Al Ahli FC (KSA)" },
			{ pos: "FW", name: "KHALID", club: "Al Ettifaq FC (KSA)" },
			{ pos: "MF", name: "ALHAJJI", club: "Neom SC (KSA)" },
			{ pos: "FW", name: "ALHAMDDAN", club: "Al Nassr FC (KSA)" },
			{ pos: "FW", name: "MANDASH", club: "Al Hilal SC (KSA)" },
			{ pos: "GK", name: "ALOWAIS", club: "Al Ula Saudi FC (KSA)" },
			{ pos: "GK", name: "ALKASSAR", club: "Al Qadsiah FC (KSA)" },
			{ pos: "MF", name: "KANNO", club: "Al Hilal SC (KSA)" },
			{ pos: "DF", name: "MOTEB", club: "Al Hilal SC (KSA)" },
			{ pos: "DF", name: "JEHAD", club: "Al Qadsiah FC (KSA)" },
			{ pos: "DF", name: "MOHAMMED", club: "Al Qadsiah FC (KSA)" },
		],
		CPV: [
			{ pos: "GK", name: "VOZINHA", club: "GD Chaves (POR)" },
			{ pos: "DF", name: "STOPIRA", club: "SCU Torreense (POR)" },
			{ pos: "DF", name: "BORGES", club: "Al Bataeh Club (UAE)" },
			{ pos: "DF", name: "LOPES", club: "Shamrock Rovers FC (IRL)" },
			{ pos: "DF", name: "LOGAN", club: "Villarreal CF (ESP)" },
			{ pos: "MF", name: "KEVIN L.", club: "FC Krasnodar (RUS)" },
			{ pos: "MF", name: "JOVANE", club: "CF Estrela Da Amadora (POR)" },
			{ pos: "MF", name: "JOÃO PAULO", club: "FC FCSB (ROU)" },
			{ pos: "FW", name: "BENCHIMOL", club: "FC Akron Tolyatti (RUS)" },
			{ pos: "MF", name: "MONTEIRO", club: "PEC Zwolle (NED)" },
			{ pos: "MF", name: "RODRIGUES", club: "Apollon Limassol (CYP)" },
			{ pos: "GK", name: "MARCIO", club: "PFC Montana (BUL)" },
			{ pos: "DF", name: "LOPES CABRAL", club: "SL Ben\u0000ca (POR)" },
			{ pos: "MF", name: "D. DUARTE", club: "PFC Ludogorets Razgrad (BUL)" },
			{ pos: "MF", name: "DUARTE", club: "Puskás Akadémia FC (HUN)" },
			{ pos: "MF", name: "Y. SEMEDO", club: "SC Farense (POR)" },
			{ pos: "MF", name: "SEMEDO", club: "AC Omonia (CYP)" },
			{ pos: "MF", name: "ARCANJO", club: "Vitória SC (POR)" },
			{ pos: "FW", name: "LIVRAMENTO", club: "Casa Pia AC (POR)" },
			{ pos: "FW", name: "RYAN", club: "Iğdır FK (TUR)" },
			{ pos: "MF", name: "DA COSTA", club: "Başakşehir FK (TUR)" },
			{ pos: "DF", name: "MOREIRA", club: "Columbus Crew (USA)" },
			{ pos: "GK", name: "DOS SANTOS", club: "San Diego FC (USA)" },
			{ pos: "DF", name: "WAGNER P.", club: "Trabzonspor (TUR)" },
			{ pos: "DF", name: "KELVIN", club: "SJK (FIN)" },
			{ pos: "MF", name: "HÉLIO", club: "Maccabi Tel-Aviv FC (ISR)" },
		],
		FRA: [
			{ pos: "GK", name: "SAMBA", club: "Stade Rennais FC (FRA)" },
			{ pos: "DF", name: "GUSTO", club: "Chelsea FC (ENG)" },
			{ pos: "DF", name: "DIGNE", club: "Aston Villa FC (ENG)" },
			{ pos: "DF", name: "UPAMECANO", club: "FC Bayern München (GER)" },
			{ pos: "DF", name: "KOUNDE", club: "FC Barcelona (ESP)" },
			{ pos: "MF", name: "KONE", club: "AS Roma (ITA)" },
			{ pos: "FW", name: "DEMBELE", club: "Paris Saint-Germain (FRA)" },
			{ pos: "MF", name: "TCHOUAMENI", club: "Real Madrid C. F. (ESP)" },
			{ pos: "FW", name: "THURAM", club: "FC Internazionale Milano (ITA)" },
			{ pos: "FW", name: "MBAPPE", club: "Real Madrid C. F. (ESP)" },
			{ pos: "FW", name: "OLISE", club: "FC Bayern München (GER)" },
			{ pos: "FW", name: "BARCOLA", club: "Paris Saint-Germain (FRA)" },
			{ pos: "MF", name: "KANTE", club: "Fenerbahçe SK (TUR)" },
			{ pos: "MF", name: "RABIOT", club: "AC Milan (ITA)" },
			{ pos: "DF", name: "KONATE", club: "Liverpool FC (ENG)" },
			{ pos: "GK", name: "MAIGNAN", club: "AC Milan (ITA)" },
			{ pos: "DF", name: "SALIBA", club: "Arsenal FC (ENG)" },
			{ pos: "MF", name: "ZAIRE EMERY", club: "Paris Saint-Germain (FRA)" },
			{ pos: "DF", name: "T. HERNANDEZ", club: "Al Hilal SC (KSA)" },
			{ pos: "FW", name: "DOUE", club: "Paris Saint-Germain (FRA)" },
			{ pos: "DF", name: "L. HERNANDEZ", club: "Paris Saint-Germain (FRA)" },
			{ pos: "FW", name: "MATETA", club: "Crystal Palace FC (ENG)" },
			{ pos: "GK", name: "RISSER", club: "RC Lens (FRA)" },
			{ pos: "MF", name: "CHERKI", club: "Manchester City FC (ENG)" },
			{ pos: "MF", name: "AKLIOUCHE", club: "AS Monaco (FRA)" },
			{ pos: "DF", name: "LACROIX", club: "Crystal Palace FC (ENG)" },
		],
		SEN: [
			{ pos: "GK", name: "Y. DIOUF", club: "OGC Nice (FRA)" },
			{ pos: "DF", name: "SARR", club: "Chelsea FC (ENG)" },
			{ pos: "DF", name: "KOULIBALY", club: "Al Hilal SC (KSA)" },
			{ pos: "DF", name: "SECK", club: "Maccabi Haifa FC (ISR)" },
			{ pos: "MF", name: "GANA", club: "Everton FC (ENG)" },
			{ pos: "MF", name: "P.I. CISS", club: "Rayo Vallecano (ESP)" },
			{ pos: "FW", name: "DIAO", club: "Como (ITA)" },
			{ pos: "MF", name: "LAMINE", club: "AS Monaco (FRA)" },
			{ pos: "FW", name: "B. DIENG", club: "FC Lorient (FRA)" },
			{ pos: "FW", name: "MANÉ", club: "Al Nassr FC (KSA)" },
			{ pos: "FW", name: "JACKSON", club: "FC Bayern München (GER)" },
			{ pos: "FW", name: "CHERIF", club: "Samsunspor (TUR)" },
			{ pos: "FW", name: "NDIAYE", club: "Everton FC (ENG)" },
			{ pos: "DF", name: "JAKOBS", club: "Galatasaray SK (TUR)" },
			{ pos: "DF", name: "KRÉPIN", club: "AS Monaco (FRA)" },
			{ pos: "GK", name: "MENDY", club: "Al Ahli FC (KSA)" },
			{ pos: "MF", name: "P.M. SARR", club: "Tottenham Hotspur FC (ENG)" },
			{ pos: "FW", name: "SARR", club: "Crystal Palace FC (ENG)" },
			{ pos: "DF", name: "NIAKHATE", club: "Olympique Lyonnais (FRA)" },
			{ pos: "FW", name: "MBAYE", club: "Paris Saint-Germain (FRA)" },
			{ pos: "MF", name: "H. DIARRA", club: "Sunderland AFC (ENG)" },
			{ pos: "MF", name: "BARA", club: "FC Bayern München (GER)" },
			{ pos: "GK", name: "DIAW", club: "Le Havre AC (FRA)" },
			{ pos: "DF", name: "A. MENDY", club: "OGC Nice (FRA)" },
			{ pos: "DF", name: "DIOUF", club: "West Ham United FC (ENG)" },
			{ pos: "MF", name: "GUEYE", club: "Villarreal CF (ESP)" },
		],
		NOR: [
			{ pos: "GK", name: "NYLAND", club: "Sevilla FC (ESP)" },
			{ pos: "MF", name: "THORSBY", club: "US Cremonese (ITA)" },
			{ pos: "DF", name: "VASSBAKK AJER", club: "Brentford FC (ENG)" },
			{ pos: "DF", name: "ØSTIGÅRD", club: "Genoa CFC (ITA)" },
			{
				pos: "DF",
				name: "MØLLER WOLFE",
				club: "Wolverhampton Wanderers FC (ENG)",
			},
			{ pos: "MF", name: "BERG", club: "FK Bodø/Glimt (NOR)" },
			{ pos: "FW", name: "SØRLOTH", club: "Atlético De Madrid (ESP)" },
			{ pos: "MF", name: "BERGE", club: "Fulham FC (ENG)" },
			{ pos: "FW", name: "BRAUT HAALAND", club: "Manchester City FC (ENG)" },
			{ pos: "MF", name: "ØDEGAARD", club: "Arsenal FC (ENG)" },
			{ pos: "FW", name: "STRAND LARSEN", club: "Crystal Palace FC (ENG)" },
			{ pos: "GK", name: "TANGVIK", club: "Hamburger SV (GER)" },
			{ pos: "GK", name: "SELVIK", club: "Watford FC (ENG)" },
			{ pos: "MF", name: "AURSNES", club: "SL Ben\u0000ca (POR)" },
			{ pos: "DF", name: "BJØRKAN", club: "FK Bodø/Glimt (NOR)" },
			{ pos: "DF", name: "HOLMGREN", club: "Torino FC (ITA)" },
			{ pos: "DF", name: "HEGGEM", club: "Bologna FC (ITA)" },
			{ pos: "MF", name: "THORSTVEDT", club: "US Sassuolo (ITA)" },
			{ pos: "MF", name: "AASGAARD", club: "Rangers FC (SCO)" },
			{ pos: "FW", name: "NUSA", club: "RB Leipzig (GER)" },
			{ pos: "MF", name: "SCHJELDERUP", club: "SL Ben\u0000ca (POR)" },
			{ pos: "MF", name: "BOBB", club: "Fulham FC (ENG)" },
			{ pos: "MF", name: "HAUGE", club: "FK Bodø/Glimt (NOR)" },
			{ pos: "DF", name: "LANGÅS", club: "Derby County FC (ENG)" },
			{ pos: "DF", name: "FALCHENER", club: "Viking Stavanger (NOR)" },
			{ pos: "FW", name: "RYERSON", club: "Borussia Dortmund (GER)" },
		],
		IRQ: [
			{ pos: "GK", name: "FAHAD", club: "Al Talaba SC (IRQ)" },
			{ pos: "DF", name: "REBIN", club: "Port FC (THA)" },
			{ pos: "DF", name: "HUSSEIN", club: "Pogoń Szczecin (POL)" },
			{ pos: "DF", name: "ZAID T.", club: "Pakhtakor Tashkent FK (UZB)" },
			{ pos: "DF", name: "AKAM", club: "Al Zawra'a SC (IRQ)" },
			{ pos: "DF", name: "MUNAF", club: "Al Shorta SC (IRQ)" },
			{ pos: "MF", name: "YOUSSEF", club: "AEK Larnaca FC (CYP)" },
			{ pos: "MF", name: "IBRAHIM", club: "Al Dhafra SCC (UAE)" },
			{ pos: "FW", name: "AL-HAMADI", club: "Luton Town FC (ENG)" },
			{ pos: "FW", name: "MOHANAD", club: "Dibba FC (UAE)" },
			{ pos: "FW", name: "AHMED Q.", club: "Nashville SC (USA)" },
			{ pos: "GK", name: "JALAL", club: "Al Zawra'a SC (IRQ)" },
			{ pos: "FW", name: "ALI Y.", club: "Al Talaba SC (IRQ)" },
			{ pos: "MF", name: "Z.IQBAL", club: "FC Utrecht (NED)" },
			{ pos: "DF", name: "AHMED", club: "Al Shorta SC (IRQ)" },
			{ pos: "MF", name: "AL-AMMARI", club: "KS Cracovia (POL)" },
			{ pos: "FW", name: "ALI J.", club: "Al Najmah SC (KSA)" },
			{ pos: "FW", name: "AYMEN", club: "Al Karma SC (IRQ)" },
			{ pos: "MF", name: "K. YAKOB", club: "Aarhus GF (DEN)" },
			{ pos: "MF", name: "AIMAR", club: "Sarpsborg 08 FF (NOR)" },
			{ pos: "FW", name: "MARKO", club: "Venezia FC (ITA)" },
			{ pos: "GK", name: "AHMED B.", club: "Al Shorta SC (IRQ)" },
			{ pos: "DF", name: "DOSKI", club: "FC Viktoria Plzeň (CZE)" },
			{ pos: "MF", name: "ZAID I.", club: "Al Talaba SC (IRQ)" },
			{ pos: "DF", name: "MUSTAFA", club: "Al Shorta SC (IRQ)" },
			{ pos: "DF", name: "FRANS", club: "Persib Bandung (IDN)" },
		],
		ARG: [
			{ pos: "GK", name: "MUSSO", club: "Atlético De Madrid (ESP)" },
			{ pos: "DF", name: "BALERDI", club: "Olympique Marseille (FRA)" },
			{ pos: "DF", name: "TAGLIAFICO", club: "Olympique Lyonnais (FRA)" },
			{ pos: "DF", name: "MONTIEL", club: "CA River Plate (ARG)" },
			{ pos: "MF", name: "PAREDES", club: "CA Boca Juniors (ARG)" },
			{ pos: "DF", name: "MARTÍNEZ", club: "Manchester United FC (ENG)" },
			{ pos: "MF", name: "DE PAUL", club: "Inter Miami CF (USA)" },
			{ pos: "MF", name: "BARCO", club: "RC Strasbourg (FRA)" },
			{ pos: "FW", name: "J. ALVAREZ", club: "Atlético De Madrid (ESP)" },
			{ pos: "FW", name: "MESSI", club: "Inter Miami CF (USA)" },
			{ pos: "MF", name: "LO CELSO", club: "Real Betis (ESP)" },
			{ pos: "GK", name: "RULLI", club: "Olympique Marseille (FRA)" },
			{ pos: "DF", name: "ROMERO", club: "Tottenham Hotspur FC (ENG)" },
			{ pos: "MF", name: "PALACIOS", club: "Bayer Leverkusen (GER)" },
			{ pos: "MF", name: "N. GONZALEZ", club: "Atlético De Madrid (ESP)" },
			{ pos: "FW", name: "ALMADA", club: "Atlético De Madrid (ESP)" },
			{ pos: "FW", name: "SIMEONE", club: "Atlético De Madrid (ESP)" },
			{ pos: "FW", name: "NICO PAZ", club: "Como (ITA)" },
			{ pos: "DF", name: "OTAMENDI", club: "SL Ben\u0000ca (POR)" },
			{ pos: "MF", name: "MAC ALLISTER", club: "Liverpool FC (ENG)" },
			{ pos: "FW", name: "LOPEZ", club: "SE Palmeiras (BRA)" },
			{
				pos: "FW",
				name: "L. MARTINEZ",
				club: "FC Internazionale Milano (ITA)",
			},
			{ pos: "GK", name: "E. MARTINEZ", club: "Aston Villa FC (ENG)" },
			{ pos: "MF", name: "E. FERNANDEZ", club: "Chelsea FC (ENG)" },
			{ pos: "DF", name: "MEDINA", club: "Olympique Marseille (FRA)" },
			{ pos: "DF", name: "MOLINA", club: "Atlético De Madrid (ESP)" },
		],
		AUT: [
			{ pos: "GK", name: "SCHLAGER", club: "FC Red Bull Salzburg (AUT)" },
			{ pos: "DF", name: "AFFENGRUBER", club: "Elche CF (ESP)" },
			{ pos: "DF", name: "DANSO", club: "Tottenham Hotspur FC (ENG)" },
			{ pos: "MF", name: "XAVER", club: "RB Leipzig (GER)" },
			{ pos: "DF", name: "POSCH", club: "1. FSV Mainz 05 (GER)" },
			{ pos: "MF", name: "SEIWALD", club: "RB Leipzig (GER)" },
			{ pos: "FW", name: "ARNAUTOVIC", club: "FK Crvena Zvezda (SRB)" },
			{ pos: "DF", name: "ALABA", club: "Real Madrid C. F. (ESP)" },
			{ pos: "MF", name: "SABITZER", club: "Borussia Dortmund (GER)" },
			{ pos: "MF", name: "GRILLITSCH", club: "SC Braga (POR)" },
			{ pos: "FW", name: "GREGORITSCH", club: "FC Augsburg (GER)" },
			{ pos: "GK", name: "WIEGELE", club: "FC Viktoria Plzeň (CZE)" },
			{ pos: "GK", name: "PENTZ", club: "Brøndby IF (DEN)" },
			{ pos: "FW", name: "KALAJDZIC", club: "LASK Linz (AUT)" },
			{ pos: "DF", name: "LIENHART", club: "SC Freiburg (GER)" },
			{ pos: "DF", name: "MWENE", club: "1. FSV Mainz 05 (GER)" },
			{ pos: "MF", name: "CHUKWUEMEKA", club: "Borussia Dortmund (GER)" },
			{ pos: "MF", name: "SCHMID", club: "SV Werder Bremen (GER)" },
			{ pos: "MF", name: "BAUMGARTNER", club: "RB Leipzig (GER)" },
			{ pos: "MF", name: "LAIMER", club: "FC Bayern München (GER)" },
			{ pos: "FW", name: "WIMMER", club: "VfL Wolfsburg (GER)" },
			{ pos: "MF", name: "PRASS", club: "TSG Hoffenheim (GER)" },
			{ pos: "DF", name: "FRIEDL", club: "SV Werder Bremen (GER)" },
			{ pos: "MF", name: "WANNER", club: "PSV Eindhoven (NED)" },
			{ pos: "DF", name: "SVOBODA", club: "Venezia FC (ITA)" },
			{ pos: "MF", name: "SCHÖPF", club: "Wolfsberger AC (AUT)" },
		],
		ALG: [
			{ pos: "GK", name: "MASTIL", club: "FC Stade Nyonnais (SUI)" },
			{ pos: "DF", name: "MANDI", club: "Lille OSC (FRA)" },
			{ pos: "DF", name: "ABADA", club: "USM Alger (ALG)" },
			{ pos: "DF", name: "TOUGAI", club: "Espérance De Tunisie (TUN)" },
			{ pos: "DF", name: "BELAID", club: "JS Kabylie (ALG)" },
			{ pos: "MF", name: "ZERROUKI", club: "FC Twente (NED)" },
			{ pos: "FW", name: "MAHREZ", club: "Al Ahli FC (KSA)" },
			{ pos: "MF", name: "AOUAR", club: "Al Ittihad (KSA)" },
			{ pos: "FW", name: "GOUIRI", club: "Olympique Marseille (FRA)" },
			{ pos: "MF", name: "CHAIBI", club: "Eintracht Frankfurt (GER)" },
			{ pos: "FW", name: "HADJ MOUSSA", club: "Feyenoord Rotterdam (NED)" },
			{ pos: "FW", name: "BENBOUALI", club: "Györi ETO FC (HUN)" },
			{ pos: "DF", name: "HADJAM", club: "BSC Young Boys (SUI)" },
			{ pos: "MF", name: "BOUDAOUI", club: "OGC Nice (FRA)" },
			{ pos: "DF", name: "AÏT NOURI", club: "Manchester City FC (ENG)" },
			{ pos: "GK", name: "BENBOT", club: "USM Alger (ALG)" },
			{ pos: "DF", name: "BELGHALI", club: "Hellas Verona FC (ITA)" },
			{ pos: "FW", name: "AMOURA", club: "VfL Wolfsburg (GER)" },
			{ pos: "MF", name: "BENTALEB", club: "Lille OSC (FRA)" },
			{ pos: "FW", name: "BOULBINA", club: "Al Duhail SC (QAT)" },
			{ pos: "DF", name: "BENSEBAINI", club: "Borussia Dortmund (GER)" },
			{ pos: "MF", name: "MAZA", club: "Bayer Leverkusen (GER)" },
			{ pos: "GK", name: "ZIDANE", club: "Granada CF (ESP)" },
			{ pos: "MF", name: "TITRAOUI", club: "Sporting Charleroi (BEL)" },
			{ pos: "FW", name: "GHEDJEMIS", club: "Frosinone (ITA)" },
			{ pos: "DF", name: "CHRGUI", club: "Paris FC (FRA)" },
		],
		JOR: [
			{ pos: "GK", name: "YAZEED", club: "Al Hussein SC (JOR)" },
			{ pos: "DF", name: "ABU HASHEESH", club: "Al Karma SC (IRQ)" },
			{ pos: "DF", name: "NASIB", club: "Al Zawra'a SC (IRQ)" },
			{ pos: "DF", name: "ABU DAHAB", club: "Al Faisaly SC (JOR)" },
			{ pos: "DF", name: "ALARAB", club: "FC Seoul (KOR)" },
			{ pos: "MF", name: "JAMOUS", club: "Al Zawra'a SC (IRQ)" },
			{ pos: "FW", name: "ABU ZRAIQ", club: "Raja Casablanca (MAR)" },
			{ pos: "MF", name: "ALRAWABDEH", club: "Selangor FC (MAS)" },
			{ pos: "FW", name: "OLWAN", club: "Al Sailiya SC (QAT)" },
			{ pos: "FW", name: "ALTAMARI", club: "Stade Rennais FC (FRA)" },
			{ pos: "FW", name: "ODEH", club: "Pyramids FC (EGY)" },
			{ pos: "GK", name: "BANI ATEYAH", club: "Al Faisaly SC (JOR)" },
			{ pos: "FW", name: "ALMARDI", club: "Al Hussein SC (JOR)" },
			{ pos: "MF", name: "RAJA'EI", club: "Al Hussein SC (JOR)" },
			{ pos: "MF", name: "SA'DEH", club: "Al Karma SC (IRQ)" },
			{ pos: "DF", name: "ABU ALNADI", club: "Selangor FC (MAS)" },
			{ pos: "DF", name: "SALEEM", club: "Al Hussein SC (JOR)" },
			{ pos: "FW", name: "SABRA", club: "NK Lokomotiva Zagreb (CRO)" },
			{ pos: "DF", name: "SA'ED", club: "Al Hussein SC (JOR)" },
			{ pos: "MF", name: "ABU TAHA", club: "Al-Quwa Al-Jawiya (IRQ)" },
			{ pos: "MF", name: "NIZAR", club: "Qatar SC (QAT)" },
			{ pos: "GK", name: "ALFAKHORI", club: "Al Wahdat SC (JOR)" },
			{ pos: "DF", name: "EHSAN", club: "Al Hussein SC (JOR)" },
			{ pos: "FW", name: "AZAIZEH", club: "Al Shabab FC (KSA)" },
			{ pos: "MF", name: "ALDAOUD", club: "Al Wahdat SC (JOR)" },
			{ pos: "DF", name: "BADAWI", club: "Al Faisaly SC (JOR)" },
		],
		POR: [
			{ pos: "GK", name: "DIOGO COSTA", club: "FC Porto (POR)" },
			{ pos: "DF", name: "N. SEMEDO", club: "Fenerbahçe SK (TUR)" },
			{ pos: "DF", name: "RÚBEN DIAS", club: "Manchester City FC (ENG)" },
			{ pos: "DF", name: "TOMÁS A.", club: "SL Ben\u0000ca (POR)" },
			{ pos: "DF", name: "DALOT", club: "Manchester United FC (ENG)" },
			{ pos: "MF", name: "MATHEUS N.", club: "Manchester City FC (ENG)" },
			{ pos: "FW", name: "RONALDO", club: "Al Nassr FC (KSA)" },
			{ pos: "MF", name: "B. FERNANDES", club: "Manchester United FC (ENG)" },
			{ pos: "FW", name: "G. RAMOS", club: "Paris Saint-Germain (FRA)" },
			{ pos: "MF", name: "BERNARDO", club: "Manchester City FC (ENG)" },
			{ pos: "FW", name: "JOÃO FÉLIX", club: "Al Nassr FC (KSA)" },
			{ pos: "GK", name: "JOSÉ SÁ", club: "Wolverhampton Wanderers FC (ENG)" },
			{ pos: "DF", name: "RENATO VEIGA", club: "Villarreal CF (ESP)" },
			{ pos: "DF", name: "G. INÁCIO", club: "Sporting CP (POR)" },
			{ pos: "MF", name: "JOÃO NEVES", club: "Paris Saint-Germain (FRA)" },
			{ pos: "FW", name: "TRINCÃO", club: "Sporting CP (POR)" },
			{ pos: "FW", name: "RAFA LEÃO", club: "AC Milan (ITA)" },
			{ pos: "FW", name: "NETO", club: "Chelsea FC (ENG)" },
			{ pos: "FW", name: "G. GUEDES", club: "Real Sociedad (ESP)" },
			{ pos: "DF", name: "JOÃO CANCELO", club: "FC Barcelona (ESP)" },
			{ pos: "MF", name: "R. NEVES", club: "Al Hilal SC (KSA)" },
			{ pos: "GK", name: "RUI SILVA", club: "Sporting CP (POR)" },
			{ pos: "MF", name: "VITINHA", club: "Paris Saint-Germain (FRA)" },
			{ pos: "DF", name: "SAMÚ", club: "RCD Mallorca (ESP)" },
			{ pos: "DF", name: "N. MENDES", club: "Paris Saint-Germain (FRA)" },
			{ pos: "FW", name: "F. CONCEIÇÃO", club: "Juventus FC (ITA)" },
		],
		COL: [
			{ pos: "GK", name: "OSPINA", club: "Atlético Nacional (COL)" },
			{ pos: "DF", name: "D. MUÑOZ", club: "Crystal Palace FC (ENG)" },
			{ pos: "DF", name: "J. LUCUMI", club: "Bologna FC (ITA)" },
			{ pos: "DF", name: "ARIAS", club: "CA Independiente (ARG)" },
			{ pos: "MF", name: "K. CASTAÑO", club: "CA River Plate (ARG)" },
			{ pos: "MF", name: "RICHARD RIOS", club: "SL Ben\u0000ca (POR)" },
			{ pos: "FW", name: "LUIS DIAZ", club: "FC Bayern München (GER)" },
			{ pos: "MF", name: "CARRASCAL", club: "CR Flamengo (BRA)" },
			{ pos: "FW", name: "CORDOBA", club: "FC Krasnodar (RUS)" },
			{ pos: "MF", name: "JAMES", club: "Minnesota United FC (USA)" },
			{ pos: "MF", name: "J. ARIAS", club: "SE Palmeiras (BRA)" },
			{ pos: "GK", name: "C. VARGAS", club: "Atlas FC (MEX)" },
			{ pos: "DF", name: "Y. MINA", club: "Cagliari (ITA)" },
			{ pos: "DF", name: "PUERTA", club: "Racing Santander (ESP)" },
			{ pos: "MF", name: "PORTILLA", club: "Athletico Paranaense (BRA)" },
			{ pos: "MF", name: "J. LERMA", club: "Crystal Palace FC (ENG)" },
			{ pos: "DF", name: "J. MOJICA", club: "RCD Mallorca (ESP)" },
			{ pos: "DF", name: "W. DITTA", club: "CF Cruz Azul (MEX)" },
			{ pos: "FW", name: "C. HERNANDEZ", club: "Real Betis (ESP)" },
			{ pos: "MF", name: "QUINTERO", club: "CA River Plate (ARG)" },
			{ pos: "FW", name: "CAMPAZ", club: "CA Rosario Central (ARG)" },
			{ pos: "DF", name: "MACHADO", club: "FC Nantes (FRA)" },
			{ pos: "DF", name: "SANCHEZ", club: "Galatasaray SK (TUR)" },
			{ pos: "GK", name: "MONTERO", club: "CA Vélez Sars\u0000eld (ARG)" },
			{ pos: "FW", name: "SUAREZ", club: "Sporting CP (POR)" },
			{ pos: "FW", name: "A. GOMEZ", club: "CR Vasco Da Gama (BRA)" },
		],
		UZB: [
			{ pos: "GK", name: "YUSUPOV", club: "PFC Navbahor Namangan (UZB)" },
			{ pos: "DF", name: "KHUSANOV", club: "Manchester City FC (ENG)" },
			{ pos: "DF", name: "ALIJONOV", club: "Pakhtakor Tashkent FK (UZB)" },
			{ pos: "DF", name: "SAYFIEV", club: "FK Neftchi Farg'ona (UZB)" },
			{ pos: "DF", name: "ASHURMATOV", club: "Esteghlal Tehran FC (IRN)" },
			{ pos: "MF", name: "MOZGOVOY", club: "Pakhtakor Tashkent FK (UZB)" },
			{ pos: "MF", name: "SHUKUROV", club: "Baniyas Club (UAE)" },
			{ pos: "MF", name: "ISKANDEROV", club: "FK Neftchi Farg'ona (UZB)" },
			{ pos: "MF", name: "XAMROBEKOV", club: "Tractor Sazi Tabriz FC (IRN)" },
			{ pos: "MF", name: "MASHARIPOV", club: "Esteghlal Tehran FC (IRN)" },
			{ pos: "MF", name: "URUNOV", club: "Persepolis FC (IRN)" },
			{ pos: "GK", name: "NEMATOV", club: "Nasaf Qarshi FC (UZB)" },
			{ pos: "DF", name: "NASRULLAEV", club: "Pakhtakor Tashkent FK (UZB)" },
			{ pos: "FW", name: "SHOMURODOV", club: "Başakşehir FK (TUR)" },
			{ pos: "DF", name: "ESHMURODOV", club: "Nasaf Qarshi FC (UZB)" },
			{ pos: "GK", name: "ERGASHEV", club: "FK Neftchi Farg'ona (UZB)" },
			{ pos: "MF", name: "KHAMDAMOV", club: "Pakhtakor Tashkent FK (UZB)" },
			{ pos: "DF", name: "ABDULLAEV", club: "Dibba FC (UAE)" },
			{ pos: "MF", name: "GANIEV", club: "Al Bataeh Club (UAE)" },
			{ pos: "FW", name: "AMONOV", club: "FK Dinamo Samarkand (UZB)" },
			{ pos: "FW", name: "SERGEEV", club: "Persepolis FC (IRN)" },
			{ pos: "MF", name: "FAYZULLAEV", club: "Başakşehir FK (TUR)" },
			{ pos: "MF", name: "ESANOV", club: "FK Buxoro (UZB)" },
			{ pos: "DF", name: "KARIMOV", club: "Surkhon FK (UZB)" },
			{ pos: "DF", name: "ULMASALIYEV", club: "OKMK FK (UZB)" },
			{ pos: "DF", name: "UROZOV", club: "FK Dinamo Samarkand (UZB)" },
		],
		COD: [
			{ pos: "GK", name: "MP ASI", club: "Le Havre AC (FRA)" },
			{ pos: "DF", name: "WAN BISSAKA", club: "West Ham United FC (ENG)" },
			{ pos: "DF", name: "KAPUADI", club: "Widzew Łódź (POL)" },
			{ pos: "DF", name: "TUANZEBE", club: "Burnley FC (ENG)" },
			{ pos: "DF", name: "BATUBINSIKA", club: "AEL FC (GRE)" },
			{ pos: "MF", name: "MUKAU", club: "Lille OSC (FRA)" },
			{ pos: "MF", name: "MBUKU", club: "Montpellier HSC (FRA)" },
			{ pos: "MF", name: "MOUTOUSSAMY", club: "Atromitos FC (GRE)" },
			{ pos: "FW", name: "CIPENGA", club: "CD Castellón (ESP)" },
			{ pos: "MF", name: "BONGONDA", club: "FC Spartak Moscow (RUS)" },
			{ pos: "FW", name: "KAKUTA", club: "AEL FC (GRE)" },
			{ pos: "DF", name: "J. KAYEMBE", club: "KRC Genk (BEL)" },
			{ pos: "FW", name: "ELIA", club: "Alanyaspor (TUR)" },
			{ pos: "MF", name: "SADIKI", club: "Sunderland AFC (ENG)" },
			{ pos: "MF", name: "TSHIBOLA", club: "Kilmarnock FC (SCO)" },
			{ pos: "GK", name: "FAYULU", club: "FC Noah (ARM)" },
			{ pos: "FW", name: "BAKAMBU", club: "Real Betis (ESP)" },
			{ pos: "MF", name: "PICKEL", club: "RCD Espanyol (ESP)" },
			{ pos: "FW", name: "MAYELE", club: "Pyramids FC (EGY)" },
			{ pos: "FW", name: "WISSA", club: "Newcastle United FC (ENG)" },
			{ pos: "GK", name: "EPOLO", club: "Standard Liège (BEL)" },
			{ pos: "DF", name: "MBEMBA", club: "Lille OSC (FRA)" },
			{ pos: "FW", name: "BANZA", club: "Al Jazira (UAE)" },
			{ pos: "DF", name: "G. KALULU", club: "Aris Limassol FC (CYP)" },
			{ pos: "MF", name: "KAYEMBE", club: "Watford FC (ENG)" },
			{ pos: "DF", name: "MASUAKU", club: "RC Lens (FRA)" },
		],
		ENG: [
			{ pos: "GK", name: "PICKFORD", club: "Everton FC (ENG)" },
			{ pos: "DF", name: "KONSA", club: "Aston Villa FC (ENG)" },
			{ pos: "DF", name: "O'REILLY", club: "Manchester City FC (ENG)" },
			{ pos: "MF", name: "RICE", club: "Arsenal FC (ENG)" },
			{ pos: "DF", name: "STONES", club: "Manchester City FC (ENG)" },
			{ pos: "DF", name: "GUEHI", club: "Manchester City FC (ENG)" },
			{ pos: "FW", name: "SAKA", club: "Arsenal FC (ENG)" },
			{ pos: "MF", name: "ANDERSON", club: "Nottingham Forest FC (ENG)" },
			{ pos: "FW", name: "KANE", club: "FC Bayern München (GER)" },
			{ pos: "MF", name: "BELLINGHAM", club: "Real Madrid C. F. (ESP)" },
			{ pos: "FW", name: "RASHFORD", club: "FC Barcelona (ESP)" },
			{ pos: "DF", name: "LIVRAMENTO", club: "Newcastle United FC (ENG)" },
			{ pos: "GK", name: "D. HENDERSON", club: "Crystal Palace FC (ENG)" },
			{ pos: "MF", name: "J. HENDERSON", club: "Brentford FC (ENG)" },
			{ pos: "DF", name: "BURN", club: "Newcastle United FC (ENG)" },
			{ pos: "MF", name: "MAINOO", club: "Manchester United FC (ENG)" },
			{ pos: "MF", name: "ROGERS", club: "Aston Villa FC (ENG)" },
			{ pos: "FW", name: "GORDON", club: "Newcastle United FC (ENG)" },
			{ pos: "FW", name: "WATKINS", club: "Aston Villa FC (ENG)" },
			{ pos: "FW", name: "MADUEKE", club: "Arsenal FC (ENG)" },
			{ pos: "MF", name: "EZE", club: "Arsenal FC (ENG)" },
			{ pos: "FW", name: "TONEY", club: "Al Ahli FC (KSA)" },
			{ pos: "GK", name: "TRAFFORD", club: "Manchester City FC (ENG)" },
			{ pos: "DF", name: "JAMES", club: "Chelsea FC (ENG)" },
			{ pos: "DF", name: "SPENCE", club: "Tottenham Hotspur FC (ENG)" },
			{ pos: "DF", name: "QUANSAH", club: "Bayer Leverkusen (GER)" },
		],
		CRO: [
			{ pos: "GK", name: "LIVAKOVIĆ", club: "GNK Dinamo Zagreb (CRO)" },
			{ pos: "DF", name: "STANIŠIĆ", club: "FC Bayern München (GER)" },
			{ pos: "DF", name: "PONGRAČIĆ", club: "ACF Fiorentina (ITA)" },
			{ pos: "DF", name: "GVARDIOL", club: "Manchester City FC (ENG)" },
			{ pos: "DF", name: "ĆALETA-CAR", club: "Real Sociedad (ESP)" },
			{ pos: "DF", name: "ŠUTALO", club: "AFC Ajax (NED)" },
			{ pos: "MF", name: "MORO", club: "Bologna FC (ITA)" },
			{ pos: "MF", name: "KOVAČIĆ", club: "Manchester City FC (ENG)" },
			{ pos: "FW", name: "KRAMARIĆ", club: "TSG Hoffenheim (GER)" },
			{ pos: "MF", name: "MODRIĆ", club: "AC Milan (ITA)" },
			{ pos: "FW", name: "BUDIMIR", club: "CA Osasuna (ESP)" },
			{ pos: "GK", name: "PANDUR", club: "Hull City FC (ENG)" },
			{ pos: "MF", name: "VLAŠIĆ", club: "Torino FC (ITA)" },
			{ pos: "FW", name: "PERIŠIĆ", club: "PSV Eindhoven (NED)" },
			{ pos: "MF", name: "PAŠALIĆ", club: "Atalanta Bergamo (ITA)" },
			{ pos: "MF", name: "BATURINA", club: "Como (ITA)" },
			{ pos: "MF", name: "P. SUČIĆ", club: "FC Internazionale Milano (ITA)" },
			{ pos: "DF", name: "JAKIĆ", club: "FC Augsburg (GER)" },
			{ pos: "MF", name: "FRUK", club: "HNK Rijeka (CRO)" },
			{ pos: "FW", name: "MATANOVIĆ", club: "SC Freiburg (GER)" },
			{ pos: "MF", name: "SUČIĆ", club: "Real Sociedad (ESP)" },
			{ pos: "DF", name: "VUŠKOVIĆ", club: "Hamburger SV (GER)" },
			{ pos: "GK", name: "KOTARSKI", club: "FC København (DEN)" },
			{ pos: "FW", name: "M. PAŠALIĆ", club: "Orlando City SC (USA)" },
			{ pos: "DF", name: "ERLIĆ", club: "FC Midtjylland (DEN)" },
			{ pos: "FW", name: "MUSA", club: "FC Dallas (USA)" },
		],
		PAN: [
			{ pos: "GK", name: "MEJÍA", club: "Club Nacional (URU)" },
			{ pos: "DF", name: "BLACKMAN", club: "ŠK Slovan Bratislava (SVK)" },
			{ pos: "DF", name: "CORDOBA", club: "Norwich City FC (ENG)" },
			{ pos: "DF", name: "F. ESCOBAR", club: "Deportivo Saprissa (CRC)" },
			{ pos: "DF", name: "FARIÑA", club: "FC Pari Nizhny Novgorod (RUS)" },
			{ pos: "MF", name: "MARTÍNEZ", club: "Hapoel Kiryat Shmona FC (ISR)" },
			{ pos: "MF", name: "J.L. RODRÍGUEZ", club: "FC Juárez (MEX)" },
			{ pos: "MF", name: "CARRASQUILLA", club: "Pumas UNAM (MEX)" },
			{ pos: "FW", name: "T. RODRÍGUEZ", club: "Deportivo Saprissa (CRC)" },
			{ pos: "MF", name: "ISMAEL", club: "Club León (MEX)" },
			{ pos: "MF", name: "BÁRCENAS", club: "Mazatlán FC (MEX)" },
			{ pos: "GK", name: "SAMUDIO", club: "CD Marathón (HON)" },
			{ pos: "DF", name: "RAMOS", club: "Puerto Cabello CF (VEN)" },
			{ pos: "DF", name: "HARVEY", club: "Minnesota United FC (USA)" },
			{ pos: "DF", name: "DAVIS", club: "CD Plaza Amador (PAN)" },
			{ pos: "DF", name: "ANDRADE", club: "LASK Linz (AUT)" },
			{ pos: "FW", name: "FAJARDO", club: "CD Universidad Católica (ECU)" },
			{
				pos: "FW",
				name: "WATERMAN",
				club: "CD Universidad De Concepción (CHI)",
			},
			{ pos: "MF", name: "QUINTERO", club: "CD Plaza Amador (PAN)" },
			{ pos: "MF", name: "GODOY", club: "San Diego FC (USA)" },
			{ pos: "MF", name: "YANIS", club: "CD Cobresal (CHI)" },
			{ pos: "GK", name: "MOSQUERA", club: "Al Fayha FC (KSA)" },
			{ pos: "DF", name: "A. MURILLO", club: "Beşiktaş JK (TUR)" },
			{ pos: "FW", name: "LONDOÑO", club: "CD Universidad Católica (ECU)" },
			{ pos: "DF", name: "MILLER", club: "Turan Tovuz (AZE)" },
			{ pos: "DF", name: "GUTIÉRREZ", club: "Deportivo La Guaira (VEN)" },
		],
		GHA: [
			{ pos: "GK", name: "ZIGI", club: "FC St. Gallen (SUI)" },
			{ pos: "DF", name: "SEIDU", club: "Stade Rennais FC (FRA)" },
			{ pos: "MF", name: "CALEB", club: "FC Nordsjælland (DEN)" },
			{ pos: "DF", name: "ADJETEY", club: "VfL Wolfsburg (GER)" },
			{ pos: "MF", name: "THOMAS", club: "Villarreal CF (ESP)" },
			{ pos: "DF", name: "SULEMAN", club: "Rayo Vallecano (ESP)" },
			{ pos: "FW", name: "FATAWU", club: "Leicester City FC (ENG)" },
			{ pos: "MF", name: "SIBO", club: "Real Oviedo (ESP)" },
			{ pos: "FW", name: "AYEW", club: "Leicester City FC (ENG)" },
			{ pos: "FW", name: "ASANTE", club: "Coventry City FC (ENG)" },
			{ pos: "MF", name: "SEMENYO", club: "Manchester City FC (ENG)" },
			{ pos: "GK", name: "ANANG", club: "St Patrick's Athletic FC (IRL)" },
			{ pos: "FW", name: "BAAH", club: "Al Qadsiah FC (KSA)" },
			{ pos: "DF", name: "MENSAH", club: "AJ Auxerre (FRA)" },
			{ pos: "MF", name: "OWUSU", club: "AJ Auxerre (FRA)" },
			{ pos: "GK", name: "ASARE", club: "Hearts Of Oak SC (GHA)" },
			{ pos: "DF", name: "BABA", club: "PAOK Saloniki (GRE)" },
			{ pos: "DF", name: "OPOKU", club: "Başakşehir FK (TUR)" },
			{ pos: "FW", name: "WILLIAMS", club: "Athletic Club (ESP)" },
			{ pos: "MF", name: "BOAKYE", club: "AS Saint-Etienne (FRA)" },
			{ pos: "DF", name: "PEPRAH", club: "OGC Nice (FRA)" },
			{ pos: "FW", name: "KAMALDEEN", club: "Atalanta Bergamo (ITA)" },
			{ pos: "DF", name: "LUCKASSEN", club: "Pafos FC (CYP)" },
			{ pos: "FW", name: "NUAMAH", club: "Olympique Lyonnais (FRA)" },
			{ pos: "FW", name: "ADU", club: "FC Viktoria Plzeň (CZE)" },
			{ pos: "DF", name: "SENEYA", club: "AJ Auxerre (FRA)" },
		],
	},
};
